### ISSUE TITLE
`cw` adds two items to the undo-history, instead of just one. (vim)

### ISSUE THREAD

**Issue by benjamin-travis-summers** [yi-editor/yi#1031]
If you use `cw` to replace a word, and then undo immediately, the changed word is deleted but the original word is not added back. `cw` is a single operation, so the whole change should be a single element of the undo-history.

Curiously, `.` behaves correctly with `cw`. If you execute a change, and then use `.` to replay the action in another location the change happens as a single operation.

**Comment by ethercrow** [comment]
Should be fixed by https://github.com/yi-editor/yi/commit/93cfa0f519edf998ed36eba386deef1c3403bd3c
