### ISSUE TITLE
Most digraphs are not supported. (vim)

### ISSUE THREAD

**Issue by benjamin-travis-summers** [yi-editor/yi#1032]
`Yi.Keymap.Vim.Digraph` defines a small subset of vim's (rfc1345) digraphs.

http://hackage.haskell.org/package/yi-keymap-vim-0.14.1/docs/src/Yi-Keymap-Vim-Digraph.html

We could fill out this list with the rest of the RFC1345 digraphs, but performance could be an issue. `glirc` (apparently) solves this by packing all the digraphs together into a big text string and using `Text.foldr` to scan it:

https://hackage.haskell.org/package/glirc-2.23/docs/src/Digraphs.html
https://hackage.haskell.org/package/glirc-2.23/docs/src/DigraphQuote.html

Would it be worth importing this solution or maybe creating a separate `rfc1345` package to solve this problem?

**Comment by benjamin-travis-summers** [comment]
Happy to do this! But, I'd like some feedback on how other people would prefer to see this done.

**Comment by ethercrow** [comment]
I don't expect performance to be a problem if we use a hashmap there.
