### ISSUE TITLE
error: Unhandled event <lt> in replace mode (vim)

### ISSUE THREAD

**Issue by benjamin-travis-summers** [yi-editor/yi#1037]
If you enter replace mode with `R`, and try to input a `<` character, then you get this error

```
error: Unhandled event <lt> in replace mode
CallStack (from HasCallStack):
  error, called at src/Yi/Keymap/Vim/ReplaceMap.
```

**Comment by ethercrow** [comment]
Should be fixed by https://github.com/yi-editor/yi/commit/5e51047943934cdb88ff1523ab3898a6829001cf

**Comment by benjamin-travis-summers** [comment]
Thanks!
