### ISSUE TITLE
"Pasting non-block string into a block selection is not implemented"

### ISSUE THREAD

**Issue by stites** [yi-editor/yi#1044]
I'd like to work on this vim-based feature:

```
aaa
^-- cursor is on 'a'
bbb
ccc
```
yank the word: `yw`, then in Visual mode:
```
aaa
^-------
bbb     \
^---------
ccc        \
^-------------- Vertical visual block on all first characters
```
next, paste with `P` to get:
```
aaaaaa
aaabbb
aaaccc
```
Instead I see the following message: "Pasting non-block string into a block selection is not implemented."

I think this is a pretty simple feature, so long as I can pre-validate that the yanked text is only a single-line (if it's a multi-line, I'll probably just repeat the message). How can I get started on this?

**Comment by noughtmare** [comment]
My bad. I used an outdated version of alacritty. Thanks!

**Comment by noughtmare** [comment]
Oops wrong tab

**Comment by noughtmare** [comment]
@ethercrow recently did some related work: https://github.com/yi-editor/yi/commit/2010ab55e6a4605c3eaf4395afdc25f0a5a63c10

**Comment by noughtmare** [comment]
This is implemented with https://github.com/yi-editor/yi/commit/ad6bb4906769e0004dcf03910cbadd41ddfcadbc
