### ISSUE TITLE
Investigate ghc-hotswap as alternative for dyre

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#1057]
Source:
https://github.com/fbsamples/ghc-hotswap

Blog post:
http://simonmar.github.io/posts/2017-10-17-hotswapping-haskell.html

**Comment by ethercrow** [comment]
Oh, shiny!

**Comment by noughtmare** [comment]
I think this is not what we want. Hot code reloading is overkill for our application. Rather a good configuration system should be used so that every user can change their editor how they like. If a feature is not yet implemented (and therefore also not yet configurable) it needs to be developed first which requires recompiling Yi anyway, so then we don't need hot code reloading. I can't see another use for hot code reloading besides changing the configuration or adding new features (which both don't necessarily require it).

Yi is not a program that is intended to be started once and then run in the background, it is intended to be started when starting to edit a file and closed when you're done.

> Oh, shiny!

I think this is what I should keep in mind: It might be cool, but that is not enough reason to start using it.
