### ISSUE TITLE
Yi.Mode.Buffers.switch: Buffer not found

### ISSUE THREAD

**Issue by talanis85** [yi-editor/yi#1060]
Steps to reproduce:
- Open yi with 2 files in different directories
- Open buffer list (Yi.Mode.Buffers.listBuffers)
- Try to switch to one of the opened files

Seems like the buffer name in the buffer list is not the actual buffer name needed by switchToBufferWithNameE.

**Comment by noughtmare** [comment]
Can you be more specific as to which commands you use to accomplish the switching of buffers? I have tried this with the vim keybindings:

```
:e ~/somedir/somefile
:e ~/someotherdir/someotherfile
:buffer somedir/somefile
:buffer someotherdir/someotherfile
```
That works just fine.

**Comment by noughtmare** [comment]
Ah, so I now tested it with emacs and indeed `listBuffers` shows the common prefix while the `switchBufferE` command only accepts buffer names without the common prefix.  

I guess there are multiple solutions to this problem:

* Don't show the common prefix in the buffer list.
* Make switchBufferE also accept buffer names with the common prefix.
