### ISSUE TITLE
How to get yi-fuzzy-open working?

### ISSUE THREAD

**Issue by varmanishant** [yi-editor/yi#1064]
I did this:

`example-configs/yi-all-static`, edited the `stack.yaml`, added `yi-rope`  to `extra-deps` , added `yi-all-static` to the `subdirs` and then did a `stack build` and `stack install`. But I still can't find the `fuzzyOpen` function in `M-x`.

Would that not be available as a function in `M-x`? Do I need to do a `keymap` in `vim` or `emacs` mode? If so how would I go about that?

```
resolver: lts-8.18
packages:
- '.'
- location: '../../'
  subdirs:
    - 'yi-core'
    - 'yi-frontend-vty'
    - 'yi-frontend-pango'
    - 'yi-fuzzy-open'
    - 'yi-language'
    - 'yi-keymap-vim'
    - 'yi-keymap-emacs'
    - 'yi-misc-modes'
    - 'yi-mode-haskell'
    - 'yi-mode-javascript'
extra-deps: [yi-rope-0.10]
```

**Comment by varmanishant** [comment]
I was able to use this [example](https://github.com/stites/yi-configs) config and make it work.

**Comment by noughtmare** [comment]
@varmanishant To give you some more information, the things that M-x lists are defined here:
https://github.com/yi-editor/yi/blob/bd91818cf33b78a92c9e669a5d7ca2282f503b31/yi-core/src/Yi/Config/Default.hs#L34-L74

If you want to add a command to the M-x menu you have to do something like this:
```haskell
import Yi.Eval (publishedActions)
import qualified Data.HashMap.Strict as HM
import Yi.Config.Simple (defaultConfig)
import Yi.Keymap -- for the makeAction function
import Control.Lens

myConfig = defaultConfig & publishedActions %~ HM.insert "myAction" (makeAction myAction)
```

**Comment by varmanishant** [comment]
Thanks @noughtmare !
