### ISSUE TITLE
shell-mode keeps suspending to shell

### ISSUE THREAD

**Issue by juhp** [yi-editor/yi#1097]
I am on Linux (fedora 28)
$ yi --version
Yi 0.18.0

Then I run yi in a terminal (gnome-terminal) and enter shell mode.

M-x shell RET

Shell mode starts as expected, but after 2 keystrokes yi suspends back to the terminal shell which seems wrong. I am return to yi (`fg`) but as soon as I type another few keys it suspends again.

**Comment by noughtmare** [comment]
Duplicate of #1063
