### ISSUE TITLE
Dead links in the blog

### ISSUE THREAD

**Issue by hexagonrecursion** [yi-editor/yi#1126]
The links to the [2014 demo](https://yi-editor.github.io/posts/2014-09-03-demo/) are dead. I was able to find [the pdf](https://web.archive.org/web/20160722103718/http://www.cse.chalmers.se/~bernardy/2008-haskell039-bernardy.pdf) on we archive, but the video is gone for good.

**Comment by noughtmare** [comment]
I think this is the video: https://www.youtube.com/watch?v=R0061WZF_YE

**Comment by noughtmare** [comment]
It's also in the ACM digital library: https://dl.acm.org/doi/10.1145/1411286.1411294

**Comment by noughtmare** [comment]
I now notice that this issue was already opened a while ago: https://github.com/yi-editor/yi-editor.github.com/issues/23
