### ISSUE TITLE
Automatic block adjustment and comments

### ISSUE THREAD

**Issue by ethercrow** [yi-editor/yi#173]
_Original author: nicolas....@gmail.com (January 12, 2009 20:52:29)_

<b>What steps will reproduce the problem?</b>
1. Open a file with the given contents :
```
$ cat > a
test = do
  a
  b
{-                                                                        

foo
  c
bar
-}
CTRL-D
$ yi a
```
2. Change the indentation of the line with &quot;a&quot;

What is the expected output?
To change only the &quot;a&quot; and &quot;b&quot; lines.

What do you see instead?
The &quot;c&quot; line is moving too :)

_Original issue: http://code.google.com/p/yi-editor/issues/detail?id=227_

**Comment by noughtmare** [comment]
This has been "solved" by https://github.com/yi-editor/yi/commit/3f6df013d500fc982e38ecc5a9993a7730b4ac2d.
