### ISSUE TITLE
Split parts of Yi into separate packages

### ISSUE THREAD

**Issue by fread2281** [yi-editor/yi#487]
Yi as it stands is a rather large package. Splitting it up would force us to ensure higher quality in some parts and would also reduce the size of the package. Some places where I see this to be a good idea:

* Data.\*, System.*: Ideally we would have nothing here. I will investigate alternate packages on hackage as replacements for these modules, and it would be a good idea to split out these into separate packages if no suitable replacement exists on hackage.
* Shim.*: As noted in #480, most if not all of this code is broken and if we were to fix it, I think we should move it into a separate package.
* Yi.Prelude: We would need to remove this or split it out to split out a lot of other code. It also hinders readability.
* Yi.Keymap.*: A very large amount of code rests here.

**Comment by ethercrow** [comment]
Done!
