### ISSUE TITLE
Non-greedy input matching in Vim2

### ISSUE THREAD

**Issue by ghost** [yi-editor/yi#518]
Currently Vim2 binding matching is greedy; having it non-greedy cold solve ambiguities (e.g. in insert mode) allowing vim-like remaps (see [this post on yi-devel](https://groups.google.com/forum/#!topic/yi-devel/zoAywWomsPA) for details).

**Comment by ethercrow** [comment]
Documented greedy parsing as intentional: https://github.com/yi-editor/yi/tree/master/yi-keymap-vim
