### ISSUE TITLE
Safer code

### ISSUE THREAD

**Issue by Fuuzetsu** [yi-editor/yi#524]
We have a lot of instances where we use ‘unsafe’ functions like `head`. While in many places the list is checked first, there are some that aren't. I'd like to encourage conversion of code into more safer forms with pattern matching and the like.

Same goes for things like `fromMaybe`.

`fromMaybe` gives a terrible error message when it fails. Here are some alternatives:

`maybe (error "maybe failed in XXX function") … foo` is already better, we know more or less where we failed.

`let Just x = foo in …` even better, if it fails, we get the reason, file, line and column numbers.

Ideal case:
```
case foo of
  Nothing -> some handling, maybe write warnings to log
  Just x -> …
```

Perhaps we should consider using some features which ensure safety statically? Length indexed vectors come to mind. What do you guys think?

This is to reduce the number of hours wasted even trying to find where the error occurred before we even get to try and find out why.

**Comment by ethercrow** [comment]
Closing as old and overly general. Concrete PRs making more code total are of course welcome.
