### ISSUE TITLE
Vim: `C-o` in insert mode allows only motions.

### ISSUE THREAD

**Issue by rgrinberg** [yi-editor/yi#531]
`C-o` in insert mode should bring you back to normal mode for a single command and then back to insert mode.

For example the following sequence in insert mode:

```
<C-o>d2b
```

Will go back to normal mode, delete 2 words backwards and then back to insert mode.

**Comment by ethercrow** [comment]
Documented as intentional: https://github.com/yi-editor/yi/tree/master/yi-keymap-vim
