### ISSUE TITLE
When terminal-width==char-count on a line, unexpected untouchable blank continuation line follows.

### ISSUE THREAD

**Issue by waynr** [yi-editor/yi#647]
**What steps will reproduce the problem?**
1. Open terminal emulator, change to 80 characters wide
2. Open yi in vim mode
3. Create 80-character line

**What is the expected output? What do you see instead?**
This is probably generalizable to any N-width line/terminal but what I see once
the number of characters is equal to the character width of the terminal screen
is an empty line that appears below this line. The cursor cannot touch this line
in vim-normal-mode.

However, in emacs mode the cursor can touch this line but only if navigated to
as if it were part of the previous line. In other words, if cursor starts at the
beginning of 80-character-wide line, pressing the down-arrow key will skip the
following line since it is actually just a wrapped continuation of the previous
line.

I think the default behavior of emacs 24.3.1 is somewhat similar in this
situation, except at column 80 it will add a visual "untouchable" character that
indicates line wrap; the 80th character on the line will then appear on the
following line.

Anyway, in vim mode I expect this non-printing, non-navigable (in normal mode)
character to not cause any line wrap. In fact, in vim 7.4 there is no
non-printing character used as a placeholder for the cursor when editing at the
end of the line--in vim, the cursor in insert mode simply overlaps the next
character, whether it's a non-printing charater or not.

For the specific example I gave if you type `A` while in normal mode on the
80-character line the cursor will overlap the next printing character which is
whatever character occurs at the start of the following line. Adding text at
this point will then lead to the 80-character line wrapping (in the default
behavior of vim), visually showing a whole new line between 80-char line and the
next line.

The additional untouchable line really won't be acceptable for anyone accustomed
to vim.

I haven't tried the pango yi interface to see if this is a problem there, but I
imagine there would be similar visual bookkeeping issues. Will comment again
once I have tried it out.

**What version of Yi are you using?**
yi 0.10.1

**What version of GHC?**
7.6.3

**What version of Cabal?**
1.20.0.3
Cabal library 1.20.0.2

**What operating system/version?**
Linux 3.11-2-amd64 #1 SMP Debian 3.11.10-1 (2013-12-04) x86_64 GNU/Linux

**Comment by jhance** [comment]
Closing this, seems like it was fixed a long time ago by #693
