### ISSUE TITLE
yi recompiles and thereafter always crashes when `lightGrey` used in config.

### ISSUE THREAD

**Issue by waynr** [yi-editor/yi#664]
**What steps will reproduce the problem?**
https://gist.github.com/waynr/64a64ef54c8a1346e2d2
1. Use the "janked" yi.hs as your configuration file and try running `yi -fvty`

What is the expected output? What do you see instead?

The only difference between the "good" and the "janked" `yi.hs` in the gist
linked above is the use of `lightGrey` instead of `defaultColor`. If this is an
invalid color, I expect to be told so. Instead, I see:

```
yi-linux-x86_64: internal error: scavenge: unimplemented/strange closure type -950725561 @ 0x7fc74ee9a6c0
    (GHC version 7.6.3 for x86_64_unknown_linux)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

```

This is interesting because Yi seems to build successfully but the binary fails
to initialize at one point or another, presumably because of something strange
about `lightGrey`. If I had to guess I would suggest that Yi has some valid
color code for this but fails to check that it is supported by my terminal.

Furthermore, if I try using the value `lightgrey` instead of `lightGrey` I see a
message similar to the following when Yi fails to re-build after detecting the
configuration change:

```
/home/waynr/.config/yi/yi.hs:16:59:
    Not in scope: `lightgrey'
    Perhaps you meant `lightGrey' (imported from Yi)
```

So lightGrey is almost certainly a valid Yi identifier.

**What version of Yi are you using?**
yi 0.10.1 (built from 7caf1cb)

**What version of GHC?**
7.6.3

**What version of Cabal?**
1.20.0.3
Cabal library 1.20.0.2

**What operating system/version?**
Linux 3.11-2-amd64 #1 SMP Debian 3.11.10-1 (2013-12-04) x86_64 GNU/Linux

**Comment by noughtmare** [comment]
This issue seems to have been fixed by time. please reopen this issue if you still have this issue.
