### ISSUE TITLE
Vim emulation : read command

### ISSUE THREAD

**Issue by alexDarcy** [yi-editor/yi#720]
In ViM, you can insert the output of a file with `:r myfile.txt`.
It can also be used to insert the output of external command, for example : `:r !ls`.

In my version, I have `Not an editor command: r`.

yi version : 0.11.1
GHC version : 7.8.3
OS : Debian unstable

**Comment by jhance** [comment]
I think the command stuff is pretty general, I think it can just output to the current buffer instead of a new one for `:r !ls`.
