### ISSUE TITLE
Using yi on ghc-less machines.

### ISSUE THREAD

**Issue by ethercrow** [yi-editor/yi#728]
I'd like to be able to compile yi (preferably with my config) and deploy the resulting binary to generic linux machines that don't have haskell machinery installed. The fact that `~/.cache/yi/yi-linux-x86_64` is 70MB stripped, doesn't help. An option to throw out hint would probably help here.

**Comment by Fuuzetsu** [comment]
If we go with lookup tables as previously discussed, turning off hint would be easy. Obviously we lose any ability to do hint-y things, at that point most likely some kind of Haskell eval which is to be expected.

**Comment by Fuuzetsu** [comment]
@ethercrow you managed to do this didn't you?

**Comment by ethercrow** [comment]
Yes, if anyone is interested, here's my setup: https://github.com/ethercrow/yi-config. `cabal install` produces an executable `e` which doesn't use dyre and doesn't depend on ghc. As a result, the only thing necessary to get this executable to work on another machine tends to be installing icu libraries.

The downside is that hint-y things and :reload are not available, but I can live with that tradeoff.
