### ISSUE TITLE
Vim keybinding append bug.

### ISSUE THREAD

**Issue by niilohlin** [yi-editor/yi#729]
Pressing 'a' in normal mode on an empty line results in the pointer going down one line and entering insert mode. Instead of just entering insert mode. This only happens if there is a line below the pointer.

**Comment by siddhanathan** [comment]
`a` uses rightB which doesn't take multiple lines into account:

https://github.com/yi-editor/yi/blob/6ac1abc3b9a765ba9b7a285c1d83301f227ddb0b/src/library/Yi/Buffer/Misc.hs#L859

**Comment by Fuuzetsu** [comment]
Hm, I thought we had a function somewhere which went forward but not beyond EOL &c…
