### ISSUE TITLE
Words with Unicode

### ISSUE THREAD

**Issue by siddhanathan** [yi-editor/yi#733]
The way Yi is splitting words with Unicode seems to be incorrect. The © symbol caused a word to be split into two, whereas, the ° symbol did not. I've tested this with Vim's `*` command in normal mode and vim tags, but I think it's general to how Yi is splitting words.

**Comment by Fuuzetsu** [comment]
Please provide test case: what do I run in GHCi or elsewhere to see the behaviour?

**Comment by siddhanathan** [comment]
For GHCi:

```
import Yi
isWordChar '©' -- False
isWordChar 'º' -- True
```

To test in the editor, open, yi, and write the following text:

`loadºini`

Then, place the curson anywhere on  `loadºini`, and call the function `readCurrentWordB`. It should be easy to test by mappping the function `readCurrentWordB >>= insertN` to a keybinding. Alternately, vim users can simply use `*` or `g*` and see what gets highlighted.

On vty, the first issue is, I can't even paste `loadºini`. The editor only pastes `loadº`. (Assuming that I paste using the OS command Ctrl-Shift-v on gnome-terminal, pasting internally in yi works fine). The second issue is, `loadºini` is recognized as one word rather than text containing two words (obviously because of the behavior of isWordChar).

Now, change the buffer contents with the following:

`load©ini`

This should now be recognized as text containing two words, which is easy to verify using `readCurrentWordB`.

This is inconsistent. Unicode characters by default are not part of a word unit. It seems strange that `º` should be considered a part of the word.

**Comment by siddhanathan** [comment]
Actually, now I think it has to do with `Data.Char`

```
import Data.Char (isAlphaNum)
isAlphaNum '©' -- False
isAlphaNum 'º' -- True
```

**Comment by siddhanathan** [comment]
I guess this really isn't an issue. Rust-lang executes the same behavior, so, this is the expected behavior defined by the Unicode Consortium.
