### ISSUE TITLE
Emacs mode, problems with selection

### ISSUE THREAD

**Issue by b0oh** [yi-editor/yi#738]
Sometimes selection behaves wrong.
If I have buffer:
```
one
two
three
```
and my cusror stays on two, I push C-space and C-n to move down, but selection starts from top or bottom of buffer.
Unfortunately I couldn't localize the problem.

**Comment by Fuuzetsu** [comment]
I know such a weird thing happens if we mix regex searches with selection, I think I had an issue around somewhere…

**Comment by b0oh** [comment]
yep, I checked, after I use C-r, it starts happening

**Comment by Fuuzetsu** [comment]
Issue #610
