### ISSUE TITLE
Reference to yi-contrib

### ISSUE THREAD

**Issue by cocreature** [yi-editor/yi#742]
I just wanted to try out yi and got confused that the link to yi-contrib in the readme is no longer working. This should either be changed to the graveyard (which sounds like a bad idea) or removed completely. Not quite sure what you prefer, so I'll leave it up to you to decide.

**Comment by siddhanathan** [comment]
Thanks for pointing that out. yi-contrib is now unmaintained, so there might be outdated code.

The most useful parts of yi-contrib was extracted into yi-fuzzy-open and yi-snippet.

The only useful example configs right now are located in https://github.com/yi-editor/yi/tree/master/example-configs and http://yi-editor.github.io/pages/vim-config/

**Comment by Fuuzetsu** [comment]
It was merely a mistake, `yi-contrib` has been killed off because there was not much in it and keeping it around was a pain. Fixed up the README now.
