### ISSUE TITLE
How do jumps work?

### ISSUE THREAD

**Issue by JonathanGallagher** [yi-editor/yi#748]
Hi,

I am trying to hook Hdevtools and Yi together.  For the most part it was really straightforward; however, there is one thing I thought would be neat -- use the jump facilities too navigate through the various errors.  Here is where I am, I can get a list:

    jscoords :: [(Int,Int)] -- jscoords is a list of row,column pairs 
                         -- returned from hdevtools indicating 
                         -- the location of errors.

Here is what I attempted to do to add the ability to jump around the errors.

    js <- withGivenBuffer bufref (mapM (\(r,c) -> pointOfLineColB r c) jscoords)
     --bufref is the BufferRef of the buffer that contains the file that was sent to hdevtools\
     --obtained using getBufferWithNameOrCurrent ""
    withEditor $ mapM addJumpAtE js

I added a small debug statement to see exactly what js is (liftBase $ putStrLn (show js)).  I got what appears to be the correct value; i.e. the number of characters into the buffer at which the error occurs.  So it seems that js contains the right information.  So I then bound jumpForwardE and jumpBackE to unused keys.

Then, fire the editor up.  Load a file with errors, and send it to hdevtools.  I get a list of errors in an error buffer (intentional).  I then switch back to the buffer with the working file in it, and hit the key bound to jumpForwardE (or jumpBackE).  In either case, I am transported to the first character in a different buffer.

For completeness here is the whole thing (with debug statements)

    checkFile :: YiM ()
    checkFile = do
        bi <- withCurrentBuffer $ bufInfoB
        bufref <- getBufferWithNameOrCurrent ""
        let name = bufInfoFileName bi
        (exitCode,cmdOut,cmdErr) <- liftBase $ runShellCommand ("hdevtools check " ++ name)
        liftBase $ putStrLn cmdOut
        withEditor $ newBufferE (MemBuffer (T.pack "errors")) (R.fromString cmdOut)
        let jscoords = processJumps cmdOut
        -- processJumps just parses strings into [(Int,Int)]
        liftBase $ putStrLn (show jscoords)
        js <- withGivenBuffer bufref (mapM (\(r,c) -> pointOfLineColB r c) jscoords)
        liftBase $ putStrLn (show js)
        withEditor $ mapM addJumpAtE js
        return ()

Any suggestions?

**Comment by ethercrow** [comment]
Try moving `newBufferE` line to the very end of this function. I suspect that `addJumpAtE` creates jump points belonging to error buffer instead of the buffer with code.

**Comment by JonathanGallagher** [comment]
Ah thank you for the tip.  I checked the source and you are right!
