### ISSUE TITLE
Support of session

### ISSUE THREAD

**Issue by Altai-man** [yi-editor/yi#758]
It would be amazing if yi will have an ability to save the current session(i.e. opened files) and restore it on the init (as an optional feature, I guess). It's quite annoying to re-open all opened buffers after reboot (for example).

**Comment by Fuuzetsu** [comment]
I suppose this shouldn't be too hard, dyre already does this when it passes the state over.

**Comment by Altai-man** [comment]
Okay, thanks for tip from where I can start. I'll try to implement it and send pull request then.

**Comment by Altai-man** [comment]
Actually, I wrote some code that saves a list of BufferIds in PersistentState, but I can't figure out how to write loadPersistentState, because of import of File.hs(which is needed to open files) causes import cycle. If I will make a pull request with a bit of code, can anyone more confident in haskell and yi help me with completing and improving of it?

**Comment by Fuuzetsu** [comment]
Just go ahead submit.

**Comment by Altai-man** [comment]
Pull request is submitted, I'll wait for review and advices.

**Comment by jhance** [comment]
I know how to unravel the dependency loop... Going to move `startEditor`, `quitEditor`, `loadPersistentState`, and `savePersistentState` to their own file

**Comment by Altai-man** [comment]
@jhance, are you going to do this changes by yourself or should someone else(like me) do it?

**Comment by jhance** [comment]
@Altai-man I was planning on it, then got busy with other things. If you want to go for it, do it!

**Comment by Altai-man** [comment]
@jhance okay, I'll try to do so tomorrow or next week and update branch. About name... I suppose something like `EditorAction.hs` may be clean enough(however it can be confused with actions inside of YiM because of `execEditorAction`). Anyway, renaming is not hard.
Is it okay that I synced branch with master and added bunch of "foreign" commits into pull request?

**Comment by jhance** [comment]
It is easier to review if you just rebase onto master and only have your own stuff in your pull request
