### ISSUE TITLE
Add FlexibleContexts to yi.cabal

### ISSUE THREAD

**Issue by gitfoxi** [yi-editor/yi#765]
So I you build with Pango and Ghc 7.10.

**Comment by Fuuzetsu** [comment]
I can build with pango and GHC 7.10.1 without FlexibleContexts in the cabal file, can you show the actual error message you get?

**Comment by gitfoxi** [comment]
I'm building from git head.

```
[ 70 of 149] Compiling Yi.Eval          ( src/library/Yi/Eval.hs, dist/build/Yi/Eval.o ) [flags changed]

src/library/Yi/Eval.hs:187:18-72:
    Non type-variable argument in the constraint: MonadBase IO m
    (Use FlexibleContexts to permit this)
    In the type signature for ‘getHintThread’:
      getHintThread :: (MonadEditor m, MonadBase IO m) =>
                       m (MVar HintRequest)
```

Not 100% sure it has to do with pango. Could be hint. I first build with default flags and then build again with pango and hint.

**Comment by ethercrow** [comment]
Reproduced by building with `-fhint`, fixed in https://github.com/yi-editor/yi/commit/bf3f25cad6720f7f946a6dbe39fc9e9a5bd0c75f.
