### ISSUE TITLE
Vim visual block append outputs an error at end of line

### ISSUE THREAD

**Issue by shak-mar** [yi-editor/yi#772]
A vimtest for this would be:
```
-- Input
(1,1)
123
-- Output
(1,1)
123text
-- Events
<C-v>$Atext<Esc>
```
I tried this by hand, and got an error in the status line:
```
error: Prelude.head: empty list
```

**Comment by Fuuzetsu** [comment]
Thought we got rid of `head` uses…

**Comment by shak-mar** [comment]
Oh, I forgot to mention, I’m using yi version `0.12.0`, from the Nix package. Did you already get rid of `head` uses in that version, or should I try again on master?

**Comment by Fuuzetsu** [comment]
That should be more than new enough, the changes I'm thinking of are old.

**Comment by siddhanathan** [comment]
There are still a few uses of `head`. This particular use of `head` can be safe. Should be a simple task: `leftEdgesOfRegionB` and `rightEdgesOfRegionB` shouldn't be capable of returning empty lists for block selections.

**Comment by ethercrow** [comment]
Should be fixed by https://github.com/yi-editor/yi/commit/51bb74cc405d11a09d2f64bbfd3c6088d75dacf8

I've also changed head to partial pattern match, this way we at least have error location in case something goes wrong.

**Comment by Fuuzetsu** [comment]
Did you consider using `NonEmpty` instead of `[]`? I already did this for some stuff in the past with great success.

**Comment by noughtmare** [comment]
Can this issue be closed?

**Comment by Fuuzetsu** [comment]
Yeah.
