### ISSUE TITLE
How to bind `jk` in insert/command mode?

### ISSUE THREAD

**Issue by rgrinberg** [yi-editor/yi#789]
I've tried:

```
imap "jk" (eval "<Esc>")
```

similar to the sample vim config but this doesn't work.

A `cmap` would be nice as well.

**Comment by ethercrow** [comment]
See https://github.com/yi-editor/yi/issues/518

**Comment by ethercrow** [comment]
Documented as intentional: https://github.com/yi-editor/yi/tree/master/yi-keymap-vim
