### ISSUE TITLE
`:cq` in Vim Mode

### ISSUE THREAD

**Issue by rgrinberg** [yi-editor/yi#790]
From my vim documentation:

```
                            *:cq* *:cquit*
:cq[uit][!]     Quit Vim with an error code, so that the compiler
            will not compile the same file again.
            WARNING: All changes in files are lost!  Also when the
            [!] is not used.  It works like ":qall!" |:qall|,
            except that Vim returns a non-zero exit code.
```

I've tried implementing this but all I see is:

https://github.com/rgrinberg/yi/blob/c2c9b95bcaf9bdb41fb63e43c7f43edafc9e6952/src/library/Yi/Core.hs#L277-L282

https://github.com/rgrinberg/yi/blob/c2c9b95bcaf9bdb41fb63e43c7f43edafc9e6952/src/library/Yi/Core.hs#L450-L456

Not really clear where to pass an exit code.

**Comment by siddhanathan** [comment]
You should be able to lift IO actions into YiM using the `io` function (defined in yi-language Yi.Utils) - it's just a synonym for liftBase.

Perhaps you could write a `quitEditorWithExitCode` function which calls `quitEditor` followed by termination with an exit code. I'm not too sure if it would be that simple.

Keep in mind that `quitEditor` calls `UI.end` which is implemented differently depending on the UI (for example, Vty uses [this](https://github.com/yi-editor/yi/blob/b811e03ea1805133796e8d8535c2b0813732450e/src/library/Yi/UI/Vty.hs#L155)). If the above doesn't work, you may need to modify `end` to accept an exit status code.
