### ISSUE TITLE
Using yi with Stack

### ISSUE THREAD

**Issue by codygman** [yi-editor/yi#793]
How can I make reload work with stack?

I'm guessing I need to wrap Dyre.wrapMain's invocation of ghc with a `stack exec --` or similar. Does this sound right? If not, any ideas?

**Comment by codygman** [comment]
Maybe rewrite wrapMain to use Stack? I'm not sure how we could make this work for the general case though. I feel like adding Stack support is aligned with the early Yi goals of "make it hackable".

**Comment by codygman** [comment]
I feel like the answer might lie within the [nix instructions](http://yi-editor.github.io/pages/installing/#Settingupmainrepository) and GHC_PACKAGE_PATH, but I'm unsure.

**Comment by siddhanathan** [comment]
Does this help? https://github.com/yi-editor/yi/issues/782#issuecomment-154117548

**Comment by ethercrow** [comment]
Personally I find it more robust to use yi with stack and without dyre.

**Comment by codygman** [comment]
Can you give your example workflow?

**Comment by ethercrow** [comment]
I clone https://github.com/ethercrow/yi-config and invoke stack install. After that I have a binary 'e' which I use as an editor.

**Comment by codygman** [comment]
@ethercrow Thanks, I'm trying out your repo now. Looks like it has some cool stuff to learn from. I would kind of like to have reloading with Dyre and wonder if it would be possible to have an environment as interactive and as self documenting as emacs.

**Comment by noughtmare** [comment]
I have created willdonnelly/dyre#30 a few days ago, but I don't think it is going to be accepted any time soon.

**Comment by ethercrow** [comment]
@codygman @noughtmare Is this resolved now or is there some outstanding issue still?

**Comment by noughtmare** [comment]
This is more an issue with dyre than with yi.
