### ISSUE TITLE
Yi doesn't add newline to end of file

### ISSUE THREAD

**Issue by sid-kap** [yi-editor/yi#794]
Vim automatically adds a newline at the end of every file, and it doesn't display the newline at the bottom. On the other hand, Yi doesn't add the newline. Also, in Yi, if I open a file that was edited in Vim, I see a blank line at the bottom.

Is this behavior intentional? I'm not sure what other editors (Emacs, etc.) do in this case.

I'd be willing to submit a PR for this as an optional feature if you guys think it is worth adding.

**Comment by siddhanathan** [comment]
EOF newline behavior is usually not set by default (the only exception is Vim). However, editors like Vim and Emacs have options to change the default behavior. So it may be worth having a flag which the user can set to enable this behavior.

**Comment by sid-kap** [comment]
Cool, I'll think about it and try to send a PR sometime this week
