### ISSUE TITLE
src/library/Yi/Editor.hs:616:58-61: No instance for (Show (Window -> WindowRef))

### ISSUE THREAD

**Issue by juhp** [yi-editor/yi#797]
yi-0.12.4 failed to build in Stackage Nightly:

```
src/library/Yi/Editor.hs:616:58-61:
    No instance for (Show (Window -> WindowRef))
      (maybe you haven't applied enough arguments to a function?)
      arising from a use of ‘show’
    In the first argument of ‘(++)’, namely ‘show wkey’
    In the second argument of ‘(++)’, namely
      ‘show wkey ++ "found. (focusWindowE)"’
    In the second argument of ‘($)’, namely
      ‘"No window with key " ++ show wkey ++ "found. (focusWindowE)"’
```

**Comment by juhp** [comment]
I think this may be caused by regex-tdfa-1.2.2.

**Comment by juhp** [comment]
Also see https://github.com/jaspervdj/hakyll/issues/420#issuecomment-215861689

**Comment by neongreen** [comment]
I think it's been fixed by https://github.com/yi-editor/yi/pull/796, which has already been merged.

**Comment by neongreen** [comment]
Perhaps a patch-level release of Yi could be made, fixing this bug? Then the constraint on regex-tdfa in Stackage could be lifted before the next Stackage LTS release.

**Comment by ethercrow** [comment]
v0.12.5 is out now

**Comment by juhp** [comment]
Thank you
