### ISSUE TITLE
Broken pango build on Ubuntu Xenial

### ISSUE THREAD

**Issue by shanemikel** [yi-editor/yi#798]
I've successfully installed Yi with stack, and now I'm trying to get it embedded with Leksah, so I've cloned this repo.  I'm doing a cabal build, and despite passing -fpango, the resulting Yi binary doesn't get the graphic frontend.

**Comment by siddhanathan** [comment]
Can you give some instructions (the commands you used) to reproduce this issue?

**Comment by ethercrow** [comment]
Closing as inactive, feel free to reopen with some more info on how to reproduce.
