### ISSUE TITLE
System clipboard interaction with the vty frontend

### ISSUE THREAD

**Issue by mmn80** [yi-editor/yi#800]
Various terminals support basic copy/paste functionality. For instance, in `gnome-terminal` you can paste with `C-S-v`, which converts the contents of the system clipboard to a sequence of keystrokes that **yi** can handle (with some lag).

The biggest problem though is copying multiple lines (by selecting with the mouse). In this case the terminal selects the entire visible line, including the padding that **vty** appends. It gets worse if you have horizontally split windows, since the terminal is oblivious to **yi**'s windows.

As a workaround, the package [Hclip](http://hackage.haskell.org/package/Hclip) can handle system clipboard for Windows, Mac and Linux. On Linux it spawns _xsel_ or _xclip_, which adds a bit of lag, on Mac it spawns _pbcopy_ / _pbpaste_, and on Windows it calls the system API.

Below is a reimplementation of `killRegion` (C-w), `killRingSaveE` (M-w) and `yankE` (C-y) from module [Yi.Keymap.Emacs.KillRing](https://github.com/yi-editor/yi/blob/master/src/library/Yi/Keymap/Emacs/KillRing.hs) that mimics the behavior of **emacs** (copy operations also copy to clipboard, and paste first checks if the clipboard is different from the top of the killring, and if it is, it inserts it there, then goes on to paste). I only tested it on Linux.

```Haskell
doCut :: YiM ()
doCut = do
  text <- withCurrentBuffer $ do
    r <- getSelectRegionB
    text <- readRegionB r
    deleteRegionB r
    return text
  io . setClipboard $ R.toString text

doCopy :: YiM ()
doCopy = do
  (r, text) <- withCurrentBuffer $ do
    r <- getSelectRegionB
    text <- readRegionB r
    assign highlightSelectionA False
    return (r, text)
  withEditor $ killringPut (regionDirection r) text
  io . setClipboard $ R.toString text

doPaste :: YiM ()
doPaste = do
  t <- io getClipboard
  let text = R.fromString t
  withEditor $ do
    text' :| _ <- uses killringA _krContents
    when (text' /= text) $ killringPut Forward text
    withCurrentBuffer $ pointB >>= setSelectionMarkPointB >> insertN text
```

I mostly post this for other people searching the issues for "clipboard" to find the workaround.

**Comment by siddhanathan** [comment]
I think the standard Vi solution is to use `"+y` to yank to the system clipboard and `"+p` to paste from the system clipboard. Its been a while, but if I remember correctly, vty support is not in yet, and currently pasting from the system clipboard is possible using the third mouse button (middle click, or triple tap) with the pango frontend. I was supposed to add the Vi yank and paste to/from clipboard to Yi a long time ago, but I was new to Haskell at the time and failed miserably. It should be fairly simple to do.

**Comment by mmn80** [comment]
You mean taking the source code of [vim](https://github.com/vim/vim) and translating to Haskell? That is a huge repo, I don't even know where to look. Ok, in the file [os_unix.x](https://github.com/vim/vim/blob/master/src/os_unix.c) alone there are 61 hits for "clipboard", tons of `#ifdef`s...
An alternative would be the source of [xclip](https://github.com/astrand/xclip), which should have only one job, UNIX style, but by the looks of it, even that has many extra features and is pretty big.

**Comment by siddhanathan** [comment]
Actually, Hclip might be a better solution. Yi currently supports the system clipboard, but it's specific to the pango frontend, and it's not bound to any keybindings.

**Comment by mmn80** [comment]
In the **Emacs** and **Cua** modes, the system clipboard should be automatically synced during the normal copy/paste operations, as in the code above. But with **vim** I haven't worked much. Does it behave like the others, or are there separate commands for say, normal copying and system clipboard copying?

Anyway, I could start a pull request and we can discuss this there if that's ok with you. I really think that this basic feature should "just work" on all frontends and all OSes through the normal bindings for the respective frontends.

If later we find ways to improve the OS interaction methods, we could rather create pull requests on **Hclip** itself, or steal the single module from there and work on it here.

**Comment by mmn80** [comment]
@ethercrow actually has a [WIP](https://github.com/ethercrow/yi/commit/43ddf03d7cd6e2d532af2b79f13b7523c1b0ee36) on this, dating Sep 18, 2015. I guess the reason he didn't push it further is the poor performance? Fair. Then what about a cabal flag that is disabled by default? Or maybe just a `Config` flag, to avoid **CPP**, the dependency being rather lightweight?

**Comment by ethercrow** [comment]
I'm starting to think that it's probably sufficient to provide `pasteFromClipboard :: YiM` and `exportRegisterToClipboard :: RegisterName -> YiM`. At least my needs as a vim user would be 100% covered by that.

Other solutions I could think of were either inefficient, calling getClipboard on every keystroke, or hard to implement.

**Comment by siddhanathan** [comment]
A not so simple approach would be to implement something like Hclip with support for yi-rope (or text) instead of String.

**Comment by mmn80** [comment]
The code above mimics the way **emacs** works and only makes system clipboard checks during copy/paste operations, not on every keystroke. Anyway, I could make a pull request with **emacs** and **cua** hooked up this way, and leave **vim** integration for **vim** users to decide later, with only the 2 functions you mentioned.
