### ISSUE TITLE
clipboard may be broken (linux, xclip)

### ISSUE THREAD

**Issue by DanBurton** [yi-editor/yi#802]
Sorry for the speculative report, but I've reported a test suite failure in Hclip that seems relevant to yi, since yi is one of the few packages that depends on it.

https://github.com/jetho/Hclip/issues/3

**Comment by siddhanathan** [comment]
Thanks for the report. Hclip 3.0.0.3 does seem to work on Linux. I'm not sure why those tests are failing.
