### ISSUE TITLE
Split packages.

### ISSUE THREAD

**Issue by ethercrow** [yi-editor/yi#814]
```
                 These depend on yi-core
                 ---------------------------------   
                 yi-frontend-pango
                 yi-frontend-vty
                 ...
yi-core
                 yi-keymap-vim
                 yi-keymap-emacs
                 ...

                 yi-mode-haskell
                 yi-mode-javascript
                 ...
```

The package yi can depend on all frontends, all keymaps and all modes. This way `cabal install yi` provides the same experience as it does right now.

User config can be a cabal project that doesn't depend on yi, but only on yi-core and necessary frontend, keymap and modes.

As far as I know, the last attempt to do such a split failed because of how difficult it was to convince ghc to find all the split packages during dynamic reconfiguration (using `:reload`). However, these days we can use stack to help with that.

These split packages would also serve as examples for people who want to make new frontends, keymaps and modes. It's not impossible right now, but they first need to look at the whole codebase and mentally decouple the part that's interesting for them.

**Comment by noughtmare** [comment]
I think we should split the project, but I think it is easier if we keep them all in one github repo. Like this:
- README.md
- LICENSE
- AUTHORS
- CHANGELOG
- ...
- components/
  - yi-core/
    - yi-core.cabal
    - src/
    - ...
  - yi-keymap-vim/
    - ...
  - yi-keymap-emacs/
    - ...
  - ...

That way we can modify multiple 'components' with one git commit.

**Comment by ethercrow** [comment]
Yes, I prefer single repo too.

**Comment by ethercrow** [comment]
Work in progress branch: https://github.com/yi-editor/yi/tree/split-packages

**Comment by noughtmare** [comment]
Great work! I think dyre should also be split from yi-core and put into it's own package.

**Comment by jhance** [comment]
Its also worth considering that its kind of odd to have `yi-mode-haskell` as a non-builtin and `yi-mode-c` as builtin. If we took out all of the modes, with the small ones in say `yi-mode-styles` could we remove the dependency of `yi-core` on `yi-language`?

**Comment by noughtmare** [comment]
"Also, I was thinking about a package yi-stock-modes for simpler modes like json and make, so that we don't end up with 100 packages here. Haskell and JavaScript are prime candidates for extraction though." ([source](https://github.com/yi-editor/yi/pull/824)) It is planned.

**Comment by noughtmare** [comment]
My proposal for 

A package `yi-keymap-core` or `yi-keymap-common` containing: 
- `Yi.TextCompletion`
- `Yi.Tag`

A package `yi-misc` containing:
- `Yi.Hoogle` (not used at all?)
- `Yi.Snippets` (not used at all?)
- `Yi.Keymap.Completion` (not used at all?)
- `Yi.Completion`

A package `yi-ireader` containing:
- `Yi.IReader`
- `Yi.Mode.IReader`

A package `yi-config` containing all configuration code.

**Comment by jhance** [comment]
The branch as-is has a small regression in that we no longer allow Vty to be configured (and instead always use the standard configuration).

This is fixable in a better way than it was working before, so I'll submit a PR for that.

**Comment by jhance** [comment]
@ethercrow Can we merge the branch? Most development has to be done inside it anyway, because of the risk of divergence causing merge issues.

**Comment by noughtmare** [comment]
I currently have this config:
```Haskell
{-# LANGUAGE OverloadedStrings #-}

import           Data.Monoid          ((<>))
import           Yi                   hiding (super)
import           Yi.Frontend.Vty      (start)
import qualified Yi.Keymap.Vim        as Vim
import qualified Yi.Keymap.Vim.Common as Vim
import qualified Yi.Keymap.Vim.Utils  as Vim
import           Yi.Mode.Haskell


main :: IO ()
main = yi $ defaultConfig
            { defaultKm = myKeymapSet
            , configCheckExternalChangesObsessively = True
            , modeTable = (myModes ++ modeTable defaultConfig)
            , startFrontEnd = start
            }

myKeymapSet :: KeymapSet
myKeymapSet = Vim.mkKeymapSet $ Vim.defVimConfig `override` \super this ->
    let eval = Vim.pureEval this
    in super {
          Vim.vimBindings = myBindings eval <> Vim.vimBindings super
        }

myBindings :: (Vim.EventString -> EditorM ()) -> [Vim.VimBinding]
myBindings _ =
    let nmap x y = Vim.mkStringBindingE Vim.Normal Vim.Drop (x, y, id)
    in [ nmap "<C-h>" previousTabE
       , nmap "<C-l>" nextTabE
       , nmap "<F3>" (withCurrentBuffer deleteTrailingSpaceB)
       ]

myModes =  [AnyMode cleverMode]
```
And I'm using the latest github version of `dyre` (which has rudimentary stack support).

**Comment by noughtmare** [comment]
Before we merge this we should also change the readme and the example configs.

**Comment by jhance** [comment]
In a technical sense we have until the release to do that, but yeah.

Is there any reason we dropped out the defaultVimConfig, etc?

**Comment by ethercrow** [comment]
I dropped defaultVimConfig from yo-core to break a circular dependency, but it should be available from yi-keymap-vim, I think.

**Comment by jhance** [comment]
Yeah, thats what I was thinking. I ended up copying it basically inline into my config, but thats not a good solution (although I dropped the part where it edits the base vty configuration to do something, not sure what that does but I was too lazy to do it...)

**Comment by jhance** [comment]
I noticed that the package split has @ethercrow directly as a maintainer instead of `yi-devel@googlegroups`, can we switch it back (makes more sense to me, so that people either post issues here or email the mailing list, rather than email one person directly)? (We can also keep the `AUTHORS` file without duplicating a bunch of them using symlinks, but I'm not sure if that would play nice with cabal or not)

**Comment by ethercrow** [comment]
I'm fine either way regarding maintainer email.
