### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#815]
It seems that these files are not used anymore:
- ~~`src/library/Parser/Incremental.hs`~~
- ~~`src/library/Yi/IncrementalParse.hs`~~
- `src/parsertest/ParserTest/ParserTest.hs`

Can they be removed or are they still used?

**Comment by noughtmare** [comment]
`src/library/Yi/Char/Unicode.hs` also seems to be unused.

**Comment by ethercrow** [comment]
Make a pull request deleting these files and let Travis check if it changes anything.
