### ISSUE TITLE
Flatten directory structure

### ISSUE THREAD

**Issue by jhance** [yi-editor/yi#830]
Our structure is weird (and different from the other yi-related projects).

Can we move `src/library -> src`, `src/test -> test`, `src/executable -> executable`?

**Comment by ethercrow** [comment]
This will be fixed by split-packages branch.

PS. sorry I'm not responding here these days, I'm pretty much swamped with stuff until 26th.

**Comment by jhance** [comment]
Ironically it seems that its already been flattened one level (by me, apparently)... Geez.
