### ISSUE TITLE
Figure out what to do about `Plated` typeclass

### ISSUE THREAD

**Issue by jhance** [yi-editor/yi#836]
(This is about `yi-language`, given that it should eventually be in this repo)

We've duplicated the `Plated` typeclass because Microlens does not provide it. There is a very good reason that it doesn't; it can maintain compatibility with Lens for most uses because *lens is based on type synonyms*. However, it doesn't provide type classes like `Plated` for the same reason that we should not use them: It makes the instances useless when used with the real `lens` library, and any functions we define polymorphically against `Plated` are only useful within Yi.

We should either:
1) Rewrite the code in a way that doesn't require us to define the `Plated` typeclass and an instance of it. Since nothing we are using externally can possibly be requiring an instance of this (because our `Plated` typeclass is not immediately compatible with the real one) this should definitely be possible.
2) Switch back to lens (although I'm clearly the only one that feels like this should be an option) and deal with having longer compilation times. I personally feel like the longer compilation times are solved by stack, not by microlens.

My stance is that I'm not necessarily against microlens but I am against adding technical debt that would not be there if we were using lens.

cc @noughtmare

**Comment by noughtmare** [comment]
The `Plated` instance is only used in `reversePattern`. Which is only used in `seBackCompiled`. Which is only used in `searchRegex`. Which is only used in `regexRegionBI`. So if we remove `searchRegex` and only allow forward searching we can remove the `Plated` instance, `reversePattern` and `seBackCompiled`.

I think instead of reversing the regex and the source we could reverse the results (in `yi-core/src/Yi/Buffer/Implementation.hs` `regexRegionBI`).

Is there another reason to allow backward searching?

**Comment by jhance** [comment]
I don't think we can do that. My assumption is that the regex list is lazy and won't have to find all results in order to find the first. However, to find the last you would probably have to find all results, which would make the initial rev-search much slower if we just reverse the results.

**Comment by noughtmare** [comment]
Matching the regex is actually faster than reversing the input. Usually the output is smaller than the input when matching regexes, so first matching the regex and then reversing the output should be faster than reversing the input and then matching (unless Yi.Rope has a much faster reverse function than Data.ByteString).

**Comment by noughtmare** [comment]
This is the code I used for testing:
```
{-# LANGUAGE OverloadedStrings #-}                                                                       
module Main where                                                                                        
                                                                                                         
import Data.Maybe                                                                                        
import Text.Regex.TDFA                                                                                   
import Text.Regex.TDFA.ByteString                                                                        
import Data.ByteString.Char8 as B                                                                        
import Data.Thyme                                                                                        
import Data.Thyme.Clock.POSIX                                                                            
import Data.AdditiveGroup ((^-^))                                                                        
import Text.Regex.Base.RegexLike                                                                         
                                                                                                         
input :: ByteString                                                                                      
input = B.unlines $ Prelude.replicate 1000000 "Hello world foo=123 whereas bar=456 Goodbye"              
                                                                                                         
main :: IO ()                                                                                            
main = do                                                                                                
  let (Right regex) = compile defaultCompOpt defaultExecOpt "foo=[0-9]+"                                 
  t0 <- getPOSIXTime                                                                                     
  rev <- return $! B.reverse input                                                                       
  t1 <- getPOSIXTime                                                                                     
  Prelude.putStrLn $ show (t1 ^-^ t0)                                                                    
  t2 <- getPOSIXTime                                                                                     
  match <- return $! matchAll regex input                                                                
  t3 <- getPOSIXTime                                                                                     
  Prelude.putStrLn $ show (t3 ^-^ t2)
```

**Comment by jhance** [comment]
Hmm, good point. Not sure why its implemented that way, then... Maybe `git blame` will add some enlightenment, but due to all the moving between repos that is quite unlikely to help.

Note that your reverse timing however is also including `B.unlines` and `Prelude.replicate` (which is acting on a list!!!) so I don't think these benchmarks are valid as-is.

(Note that in the future you might consider using criterion for benchmarking, as its quite nice)

**Comment by noughtmare** [comment]
I have updated my comment, does this fix the bug?
I needed a quick fix and didn't have the time (and motivation) to learn criterion, but I will definitely learn it soon.

**Comment by jhance** [comment]
No. You need to ensure that the result of input is evaluated to at least whnf (which should be sufficient because it's a lazy bytestring) before starting the timing.

**Comment by jhance** [comment]
Err I meant strict, not lazy, and cannot edit my comment because mobile.

**Comment by noughtmare** [comment]
Ok now it works.

**Comment by jhance** [comment]
Did you notice any difference in the timing result from the change? I'm honestly still unsure about whether or not your change did anything due to how the desugaring of do notation works. I think I would ensure it is evaluated somehow. I'm sure there is a function that does so somewhere...

**Comment by noughtmare** [comment]
before:
```
0.242697s
0.000173s
```
after (I also made the regex compilation strict)
```
0.030621s
0.000105s
```

**Comment by jhance** [comment]
(Although if there was a noticeable change in the timing, I would believe it. I just need to figure out what a bang pattern in a monadic let actually does...)

**Comment by jhance** [comment]
Ok yeah, so we still see it being slower but not as slower. Seems fine to me. I wonder if @ethercrow knows anything about why the existing implementation is as is

**Comment by noughtmare** [comment]
(Although just trying things seems to work, I should really look into lazy evaluation and strictness in haskell)

**Comment by jhance** [comment]
Actually, can you please ensure we evaluate the result of matchAll to nf?

**Comment by jhance** [comment]
I'm sure lots of us including me are in that boat! Luckily trying things usually works.

**Comment by noughtmare** [comment]
I'm pretty sure it's correct now.

**Comment by jhance** [comment]
You are evaluating the result of `matchAll` to WHNF not NF.

**Comment by noughtmare** [comment]
Criterion:
```Haskell
{-# LANGUAGE OverloadedStrings #-}                                                                       
module Main where                                                                                        
                                                                                                         
import Data.Maybe                                                                                        
import Text.Regex.TDFA                                                                                   
import Text.Regex.TDFA.ByteString                                                                        
import Data.ByteString.Char8 as B                                                                        
import Data.Thyme                                                                                        
import Data.Thyme.Clock.POSIX                                                                            
import Data.AdditiveGroup ((^-^))                                                                        
import Text.Regex.Base.RegexLike                                                                         
import Criterion.Main                                                                                    
                                                                                                         
input :: Int -> ByteString                                                                               
input n = B.unlines $ Prelude.replicate n "Hello world foo=123 whereas bar=456 Goodbye"                  
                                                                                                         
regex :: Regex                                                                                           
regex = fromRight $ compile defaultCompOpt defaultExecOpt "foo=[0-9]+"                                   
  where                                                                                                  
    fromRight (Right a) = a                                                                              
                                                                                                         
main = defaultMain [ bgroup "reverse" [ bench "1" $ nf B.reverse (input 1)                               
                                      , bench "1000" $ nf B.reverse (input 1000)                         
                                      , bench "1000000" $ nf B.reverse (input 1000000)                   
                                      ]                                                                  
                   , bgroup "regex"   [ bench "1" $ nf (uncurry matchAll) (regex, input 1)               
                                      , bench "1000" $ nf (uncurry matchAll) (regex, input 1000)         
                                      , bench "1000000" $ nf (uncurry matchAll) (regex, input 1000000)   
                                      ]                                                                  
                   ]
```
Output:
```
benchmarking reverse/1
time                 55.24 ns   (55.17 ns .. 55.30 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 55.24 ns   (55.17 ns .. 55.34 ns)
std dev              268.4 ps   (192.9 ps .. 430.0 ps)

benchmarking reverse/1000
time                 29.34 μs   (29.25 μs .. 29.48 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 29.33 μs   (29.25 μs .. 29.54 μs)
std dev              382.0 ns   (148.5 ns .. 738.2 ns)

benchmarking reverse/1000000
time                 29.48 ms   (27.72 ms .. 30.53 ms)
                     0.975 R²   (0.911 R² .. 1.000 R²)
mean                 31.16 ms   (30.30 ms .. 34.31 ms)
std dev              3.081 ms   (668.5 μs .. 5.683 ms)
variance introduced by outliers: 40% (moderately inflated)

benchmarking regex/1
time                 2.953 μs   (2.948 μs .. 2.959 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.955 μs   (2.952 μs .. 2.960 μs)
std dev              12.85 ns   (9.821 ns .. 16.02 ns)

benchmarking regex/1000
time                 2.664 ms   (2.658 ms .. 2.672 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.663 ms   (2.661 ms .. 2.669 ms)
std dev              12.35 μs   (8.235 μs .. 20.48 μs)

benchmarking regex/1000000
time                 2.668 s    (2.664 s .. 2.670 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.664 s    (2.663 s .. 2.665 s)
std dev              1.608 ms   (0.0 s .. 1.855 ms)
variance introduced by outliers: 19% (moderately inflated)
```
Surely this code is right?

**Comment by jhance** [comment]
It looks okay to me. It has the "its evaluating `input` inside the benchmark" problem which adds a bit of time, but it should add the same amount to both test runs.

If I'm reading this right, it looks like the regex is actually slower in this benchmark?

Another thing you could do: Reverse the result of the regex search and evaluate the first element to nf. This simulates just getting a single result using a reverse-search. I hypothesize that this is approximately the same as evaluating the entire match list.

**Comment by noughtmare** [comment]
[This benchmark](https://wiki.haskell.org/Regular_expressions#Sample_benchmark) has a different result from the criterion benchmarks I just did, maybe they also didn't force NF.

**Comment by jhance** [comment]
It says they used a lazy bytestring, maybe theres a difference there?

**Comment by noughtmare** [comment]
I just tested the first example, but then with `deepseq`'s `force` and It gave this result:
```
0.029627s
2.912256s
```
So I think reversing is indeed faster.

**Comment by noughtmare** [comment]
Using `TFDA.Lazy` and `ByteString.Lazy.Char8` yielded me this:
```
1.301118s
3.709515s
```

**Comment by jhance** [comment]
The performance regression on the reverse there is a bit scary.

**Comment by noughtmare** [comment]
I have made a new repo to test things: [noughtmare/regex-testing](https://github.com/noughtmare/regex-testing)

**Comment by noughtmare** [comment]
I have updated my benchmarks with parallelism. It sped up the regex matching of tdfa by ~100x. I also used Data.Text.reverse instead of Data.ByteString.Char8.reverse and it showed a decrease in speed by ~10x.

**Comment by noughtmare** [comment]
Updated my repo, now reverse is about 15 times faster than the tdfa matcher.

**Comment by noughtmare** [comment]
I have acquainted me more with lenses and now I think I have found a way to remove the ad-hoc plated implementation.

Change:
```Haskell
-- | Reverse a pattern. Note that the submatches will be reversed as well.
reversePattern :: (Pattern, (t, DoPa)) -> (Pattern, (t, DoPa))
reversePattern (pattern,(gi,DoPa maxDoPa)) = (transform rev pattern, (gi,DoPa maxDoPa))
    where rev (PConcat l) = PConcat (reverse l)
          rev (PCarat  x) = PDollar x
          rev (PDollar x) = PCarat  x
          rev (PEscape {getDoPa = dp, getPatternChar = '<'}) = PEscape {getDoPa = dp, getPatternChar = '>'}
          rev (PEscape {getDoPa = dp, getPatternChar = '>'}) = PEscape {getDoPa = dp, getPatternChar = '<'}
          rev x           = x
```
To:
```Haskell
-- | Reverse a pattern. Note that the submatches will be reversed as well.
reversePattern :: (Pattern, (t, DoPa)) -> (Pattern, (t, DoPa))
reversePattern (pattern,(gi,DoPa maxDoPa)) = (rev pattern, (gi,DoPa maxDoPa))
    where rev (PConcat l) = PConcat (reverse (map rev l))
          rev (PCarat  x) = PDollar x
          rev (PDollar x) = PCarat  x
          rev (PEscape {getDoPa = dp, getPatternChar = '<'}) = PEscape {getDoPa = dp, getPatternChar = '>'}
          rev (PEscape {getDoPa = dp, getPatternChar = '>'}) = PEscape {getDoPa = dp, getPatternChar = '<'}
          rev x           = x
```
And then the Plated instance is unnecessary.
I am not a lens expert, but at least it type-checks. Someone who knows more about lenses should check this solution. I will also try to make some tests.

**Comment by noughtmare** [comment]
This can be closed.
