### ISSUE TITLE
Use parser combinators instead of regexes

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#839]
Of course we still need to allow the user to use regexes, but I think all the searching inside the project should be done with parser combinators.

Advantages to parser combinators:
- Easier to read
- Type safe

**Comment by jhance** [comment]
As long as its not performance-sensitive, this is a good idea.

Its also a good idea to decide whether we want to use Attoparsec or Parsec. We currently use Parsec but I think there was a motion to switch to Attoparsec.

**Comment by noughtmare** [comment]
I think we should use [megaparsec](https://github.com/mrkkrp/megaparsec), because it's overall [better than parsec](https://github.com/mrkkrp/megaparsec#megaparsec-and-parsec) and we don't need the speed of attoparsec (for most of our code).

**Comment by jhance** [comment]
We also don't really need great error messages either, though... I'd have to take a better look at megaparsec to evaluate
