### ISSUE TITLE
Some block selection commands don't work right

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#840]
Pressing c should remove the selection and then start insert mode on multiple lines, now it only starts insert mode on the topmost line.

Pasting doesn't work at all (#732).

the `replaceBinding` doesn't work right with overhanging text:
Pressing `r` and then `x` on

```
testtes*tte*st
test
testtes*tte*st
```

(Asterisks denote the block selection)
Should yield:

```
testtesxxxst
test
testtesxxxst
```

But now it yields:

```
testtesxxxst
test
testxxxttest
```

Might be related to #773.

**Comment by jhance** [comment]
I don't understand what you are saying about `c`. What do you mean by insert mode on multiple lines?

**Comment by jhance** [comment]
Given that `i` doesn't work in `Ctrl-V` it doesn't seem like we have multi-insert support right now so this is nontrivial.

**Comment by noughtmare** [comment]
`I` (uppercase) does work with a visual block selection (in haskell mode). So editing multiple lines at the same time is possible.

**Comment by ethercrow** [comment]
Should be fixed by https://github.com/yi-editor/yi/commit/9df51b8a48a1a4fed3ecc2fa2e21d5ce0f8dba75
