### ISSUE TITLE
split Dyre

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#851]
Advantages of Dyre:
- "Easier" installation and configuration.

Disadvantages of Dyre:
- Doesn't have proper stack support (which makes installation and configuration more complicated than it needs to be)
- Obfuscates source code (It makes it slightly more difficult to find out where the actual Yi program starts, this is a very small disadvantage)
- Dyre isn't developed actively and has open issues ([like non atomic compilation](https://github.com/willdonnelly/dyre/issues/21))

Alternative:
We could make a github repo for the default yi configuration. To install Yi the user just have to clone the default yi configuration repo and run `stack install` inside the cloned directory. Recompilation is as easy as running `stack install` again.

If users still want dynamic recompilation they should still be able add it in their configuration.

**Comment by jhance** [comment]
Personally I don't feel like dyre became harder to use post-stack, actually it was easier (no need to the hacky shell scripts I used for sandboxes)

**Comment by jhance** [comment]
FYI splitting dyre is probably blocked on my options patch (as currently you can't add the dyre options to the argparser unless you are in yi-core)

It would probably be out by now but I played monster hunter a bit too much

**Comment by noughtmare** [comment]
#887 is an example of how dyre makes configuration more complicated.

**Comment by ethercrow** [comment]
Now that we have static and dynamic configs, the next step is extract the part of yi-core that depends on Dyre into a separate package and make dynamic configs depend on that.

**Comment by ethercrow** [comment]
https://github.com/yi-editor/yi/pull/986
