### ISSUE TITLE
Implement Buffer-local custom state

### ISSUE THREAD

**Issue by jhance** [yi-editor/yi#856]
Keymaps have access to `EditorM` for state, but there might be aspects of state which are particular to a buffer that a keymap might want to care about.

Another example of this (more practical) is #853. Since #853 is probably going to be implemented in `yi-core`, we could modify the `BufferImpl` constructor directly but we should probably take a more general approach (because not everything is in `yi-core`)

What I'm envisioning is having a `YiBufferVariable` nullary typeclass which is the `BufferM` equivalent of `YiVariable`. It will need `Default, Binary, Typeable`. We should be able to modify these and obtain their values from within `BufferM` instead of `EditorM`.

Maybe some things (tagstack?) should already be in buffer-local. (Is the vim tagstack buffer-local). [Actually, tagstack maybe should be *window*-local]

**Comment by ethercrow** [comment]
What about getBufferDyn?

Yes, tagstack is window-local.

**Comment by jhance** [comment]
Okay, so this already exists.

However it uses the `YiVariable` class which is confusing. Maybe instead this task should be to separate the two at the type level.

**Comment by jhance** [comment]
Actually, I'm not sure if `YiBufferVariable` vs `YiVariable` is useful, so closing.
