### ISSUE TITLE
[Split Packages TODO] Hint support

### ISSUE THREAD

**Issue by jhance** [yi-editor/yi#868]
This should be as easy as re-adding the flag to `package.yaml` in `yi-core` and setting it to default for the same default as before.

**Comment by jhance** [comment]
It might also be possible to split hint into a separate package

**Comment by noughtmare** [comment]
This is solved by #880, but critical errors (#870) still need to be solved.

**Comment by jhance** [comment]
Closing since we have issues for other parts
