### ISSUE TITLE
update docs for using w/ stack and cabal sandboxes

### ISSUE THREAD

**Issue by erantapaa** [yi-editor/yi#869]
The recipe for installing yi using a cabal sandbox [(link)][1] says to use:

    $ cabal exec ./dist/build/yi/yi

to start yi. However, I think the correct command (tested with cabal-1.22.8.0) is simply:

    $ cabal exec yi

Also, for the stack recipe, it  should mention that the way to invoke yi is:

    $ stack exec yi

  [1]: http://yi-editor.github.io/pages/installing/#InstallinginsideaCabalsandbox

**Comment by jhance** [comment]
Its actually `stack exec yi --package yi`

**Comment by noughtmare** [comment]
The documentation has been updated.
