### ISSUE TITLE
`:yi printMsg "hello"` error

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#872]
> [...] and trying to execute yi printMsg > "hello" results in:

>error: WontCompile [GhcError {errMsg = "<interactive>:2:1:\n    No instance for (Show x0) arising from a use of `makeAction'\n    The type variable `x0' is ambiguous\n    Note: there are several potential instances:\n      instance Show a => Show (Maybe a) -- Defined in

>Then it goes beyond the screen.

copied from #865

**Comment by jhance** [comment]
Maybe an overloaded strings related issue?

**Comment by noughtmare** [comment]
That's what I thought as well, but the `printMsg` function has the type `printMsg :: MonadEditor m => Data.Text.Internal.Text -> m ()` (when viewed with `:help printMsg`).

**Comment by jhance** [comment]
Hm...

**Comment by noughtmare** [comment]
running `:yi YiA (withEditor_ $ printMsg "hello")` probably works better, but gives the same error as #870

**Comment by noughtmare** [comment]
I have confirmed it: `:yi EditorA $ printMsg "hello"` is the right command (See https://github.com/yi-editor/yi/issues/870#issuecomment-237986556 to find out how I got `hint` to work).
