### ISSUE TITLE
Update example-configs

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#873]
I think the example-configs should use stack by default.

**Comment by jhance** [comment]
They also don't work with the split branch at all

**Comment by ethercrow** [comment]
OK, I've got my config working with split-packages branch and travis testing. Next step is to make similar configs for all keymaps and frontends, I guess they should be called something like "yi-vim-vty-static". I haven't tried using a dynamic config (with dyre) yet.

**Comment by noughtmare** [comment]
Please look at #882 If you haven't done that already. 

Do you also think that the lens based configuration is the way to go? I thought it might be harder to understand, but much easier to use.

**Comment by ethercrow** [comment]
I don't really have an opinion on lens-based configuration. I think right now the biggest pain point in writing configs is figuring out what you can configure, not whether the syntax is lens-y or record-y.

**Comment by jhance** [comment]
The reason I wanted to switch to a lens-based configuration by default is that not everything actually has a corresponding record, but everything has a lens.

**Comment by jhance** [comment]
Is this the last thing thats blocking a release?

**Comment by ethercrow** [comment]
I'm aiming to publishing yi-vim-vty-static and yi-emacs-vty-static today. Maybe pango variants if I'm lucky.

If anyone knows how to make a config with split-packages and dyre, please go ahead and commit that.
