### ISSUE TITLE
Update github milestones

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#874]
The current milestone (0.10) is already reached.
I would like a new milestone called `0.13 split-packages` (or something like that), then It can be made more clearly visible which issues need to be resolved before we can merge the `split-packages` branch.

Alternatively a new tag named `split-packages` can be added.

**Comment by noughtmare** [comment]
Issues that should be added to the milestone (or tag) are:
- #873 
- #867 
- #868 
- #869

**Comment by jhance** [comment]
Disagree with #851, splitting dyre is not blocking and doesn't add much dependencies to `yi-core` (even if its nice to split). Its a nice thing to have done but not crucial.

**Comment by noughtmare** [comment]
True
