### ISSUE TITLE
Derive Binary directly in Yi.Tag

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#875]
I don't know what the disadvantages are, but it would make the code simpler.

An example:
change
```Haskell
newtype Tag = Tag { _unTag :: T.Text } deriving (Show, Eq, Ord)
instance Binary Tag where
  ...
```
to
```Haskell
{-# GeneralizedNewtypeDeriving #-}
newtype Tag = Tag { _unTag :: T.Text } deriving (Show, Eq, Ord, Binary)
```

**Comment by noughtmare** [comment]
This would work for Binary, but would Tags would still require a Generic instance for the YiVariable instance.

**Comment by jhance** [comment]
Probably a remnant of when we couldn't use `GeneralizedNewtypeDeriving`. Feel free to fix.
