### ISSUE TITLE
Add defaultConfigs to the keymaps again.

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi#882]
When the keymaps got split, the defaultConfigs were lost. They need to be re-added before #873 can be solved.

**Comment by jhance** [comment]
I was thinking about this. I thought it makes sense to define some newtypes like

```
newtype FrontendConfig = FrontendConfig (Config -> Config)

newtype KeymapConfig = KeymapConfig (Config -> Config)
```

And then like
```
defaultConfig :: FrontendConfig -> KeymapConfig -> Config
```

So that you could do like `defaultConfig vty vim` or something to get the default config for vty+vim

**Comment by noughtmare** [comment]
I'm currently reimplementing them as they were (but in a different module).

I'm not sure about your idea, the newtypes don't seem necessary and the configure function is just function application. You could just do `(vty . vim) def` instead of `configure vty vim`.

**Comment by jhance** [comment]
I mean, its purely an abstraction. By providing a function like that it is made clear to the user what they need to do to get their configuration hooked up with a frontend and a keymap.

The old implementation is bad because it relies on `#ifdef` with flags.

**Comment by noughtmare** [comment]
It's true that your solution makes it clearer for the user what they need to do, but it also makes it less clear what is actually happening. 

The ifdef's were not really necessary; my code will be ifdef-free.

**Comment by noughtmare** [comment]
Maybe something like:
```Haskell
data Configurator = Configurator 
  { frontend :: Config -> Config
  , keymap :: Config -> Config
  }

configure :: Configurator -> Config
configure (Configurator f k) = (f . k) def
```
That way it's clear what needs to be done and it's clearer what is being done.

**Comment by noughtmare** [comment]
I think just doing the function application in the example-configs would show the user enough information to know how to do it herself.
```Haskell
myConfig :: Config -> Config
myConfig cfg = cfg { someKey = someVal }

main :: IO ()
main = yi $ (myConfig . vim . vty) def
```
That way the user can also add her own configuration function easily.

**Comment by noughtmare** [comment]
The config can then also be modified so that it uses yi-misc-modes:
```Haskell
main :: IO ()
main = yi $ (myConfig . miscModes . vim . vty) def
```

**Comment by jhance** [comment]
We should be encouraging most modifications to be done in a `ConfigM` actually (because this allows sweet lens setting syntax DSL for custom config vars). Maybe we should modify all of the stuff to be `ConfigM` and the user does

```
main = blahblahblah $
    configureVim
    configureVty
    configureMiscModes
```

**Comment by noughtmare** [comment]
`blahblahblah` would be `configMain defaultConfig` right?

**Comment by jhance** [comment]
SGTM although I can't remember exactly lol

(Sorry, bit busy this week, its hackweek at Dropbox, which is like a weeklong hackathon)
