### ISSUE TITLE
Visual mode doesn't work on text objects (vim)

### ISSUE THREAD

**Issue by Hi-Angel** [yi-editor/yi#887]
As title says… When I press "v" in normal mode *(vim keymap)*, it immediately starts selection instead of waiting for a text object.

I'm sorry, I actually didn't want to report a bug, I tried to fix it for getting more familiar with the code, and I even wrote some code for Operators.hs. But the problem is that I stuck on removing the old keybinding. I grepped all over the code for `"v"`,`'v'`, and even a regexp `".*v.*"`, I removed everything seemingly relevant; however after compilation "v" starts selection again and again.

How do I remove that old keybinding? I asked on IRC, but nobody seem to know anything. I also tried asking on mailing list one or two days ago, but my mails for some reason didn't appear there.

**Comment by jhance** [comment]
Are you using dyre?

If so, did you remember to remove your cached yi binary? If you don't remove it, and you don't change your config, all your changes have no effect.

Sorry, I'm not often on IRC and I should be on it more.

**Comment by noughtmare** [comment]
Yi is lacking the ability to select text object. I think this should be added as a  visual mode map (i.e. a binding that works only in visual mode).

**Comment by Hi-Angel** [comment]
@jhance is it `~/.cache/yi/yi-linux-x86_64`? I didn't because after every rebuild I see a message about recompilation of it anyway. Anyway, I just removed it, it was recompiled, and "v" still starts selection.

**Comment by Hi-Angel** [comment]
@noughtmare I already found how to do it, it's pretty easy. There's a file `Operator.hs`, it have commands to work specifically on text objects, e.g. "d", "c", etc. It's just have to be added there.

**Comment by noughtmare** [comment]
The issue is probably related to the fact that you're not using your custom yi project in your configuration. How do you build your customized yi project, do you use stack or cabal? Is your configuration (`~/.config/yi`) inside a stack or cabal sandbox?

**Comment by Hi-Angel** [comment]
@noughtmare I have only a single Yi source code, cloned from here. To build it I use `cabal build`, then running the resulting executable from the `dist/build/yi/yi` directory. I did use *stack* for experimenting in the office, but here I don't even have it installed.

**Comment by Hi-Angel** [comment]
@noughtmare perhaps you misunderstood me: I don't want to remove that old keybinding from the `~/.config/yi/yi.hs`, I'm trying to remove it from the source code of the editor. I.e. I'm trying to fix visual mode to work on text objects, and as a part of that I have to remove the old keybinding, which I didn't manage to do yet.

**Comment by noughtmare** [comment]
When you launch yi, it checks if your configuration has changed and recompiles *the configuration* if necessary. The configuration will use the (systemwide) installed version of yi when recompiling (so it won't use your custom yi). To make the custom yi configuration use your custom yi, you have to run `cabal install` (I mainly use stack so this might be wrong) in your custom project to install it systemwide.

I like to use stack, because you can explicitly say which yi you want to use (cabal also has some other issues). I can't easily explain how to get yi working with stack, but we're working on simplifying the installation and configuration process (so even if I would explain it now it will change soon).

**Comment by Hi-Angel** [comment]
Wow, you're right! After `cabal install` and removing the `~/.cache/yi/yi-linux-x86_64` once again, selection disappeared! So, I fixed the problem with `ln -s ~/.cabal/bin/ dist/build/yi` ^^

Yeah, I know about *cabal hell* issue which led to stack creation, but with regard to Haskell in closest time I'm planning to work only with Yi to set it in more or less usable state to replace my Emacs+Evil before moving on. So *cabal hell* hardly would be a problem, at least not very soon.

**Comment by Hi-Angel** [comment]
Turned out I was wrong — `ln -s` didn't do the trick because there're other dirs, besides binaries. And as `cabal install` more time consuming than `stack install`, I switched to stack.

I'm wondering: can I build yi for profiling without installing profiling libs *(i'm not interested in anything besides Yi)*? It's that I'm stuck: method `switchModeE $ Visual Inclusive` works different for me than it [does here](https://github.com/yi-editor/yi/blob/4725555934e5bd36704b12d7a35706b5687a9763/src/library/Yi/Keymap/Vim/NormalMap.hs#L232) *(specifically, though it changes mode name, but visual selection doesn't appear)*. So I thought, perhaps something executed higher the stack changes the behavior there. I wanted to look at stacktrace, and that's why I need to compile with profiling support. But, adding `-prof` option triggers stack's complaints about libraries not built for profiling.

**Comment by noughtmare** [comment]
[We have profiling instructions](https://github.com/yi-editor/yi#profiling), but I don't know if they're up to date. I have never really done Haskell profiling, so I can't help you with that.

I think you also need to `enableVisualE` to start the selection. I don't know why it's not exported, but [here's the source](https://github.com/yi-editor/yi/blob/4725555934e5bd36704b12d7a35706b5687a9763/src/library/Yi/Keymap/Vim/NormalMap.hs#L432-L437).

**Comment by jhance** [comment]
I believe those profile instructions were up to date, at least prior to the split packages.

**Comment by Hi-Angel** [comment]
Yay, thank you very much, it works now!

I have a question though. I'm afraid whether removing [this line](https://github.com/yi-editor/yi/blob/4725555934e5bd36704b12d7a35706b5687a9763/src/library/Yi/Keymap/Vim/NormalOperatorPendingMap.hs#L128) would break anything; does anybody know, what the `parseOperand` function does?

**Comment by Hi-Angel** [comment]
Shall I make a separate file for sole purpose of `enableVisualE` function? It can not be exported from where it is now, because `Module imports form a cycle`, as ghc says. I tried also to move it into `VisualMap.hs`, but then `Module imports form a cycle` for *Operator.hs* file. I don't see an appropriate place besides those two files.

**Comment by jhance** [comment]
SGTM

**Comment by Hi-Angel** [comment]
In fact it is possible to just copy the function into `Operator.hs` *(that's what I did to check that it worked)*, but I think that would be wrong.

**Comment by jhance** [comment]
No copy pasterino

**Comment by jhance** [comment]
Btw can you confirm to me what the bug is? In vim if I press `v` it immediately enters election and then I can press e.g. `w` to select a word.

**Comment by Hi-Angel** [comment]
Yes. And if you press `vi(` inside braces, it would select everything inside braces, while Yi didn't *(it will now ^^)*.

Sorry, I gtg now.

**Comment by Hi-Angel** [comment]
Btw, `vw` selects not quite a word, it select everything from the point till the beginning of the next word. To select word at point in vim you have to press `viw` *(which didn't work in `Yi` either)*.

**Comment by jhance** [comment]
Ok I see.

So it shouldn't affect the transition to visual mode then right? It should just be the `i(`

**Comment by Hi-Angel** [comment]
I'm not sure I understood you, but I just made it an operator, like `d` or `c` is, i.e. it simply accepts a region, enables visual selection, and stretches the selection to the region.

**Comment by noughtmare** [comment]
@Hi-Angel `viw` is just a combination of two commands: `v` to switch to visual mode and `iw` to select the 'inner word' text object. The reason that it doesn't work in Yi is that Yi doesn't have the ability to select text objects in visual mode.

@jhance [this site](http://blog.carbonfive.com/2011/10/17/vim-text-objects-the-definitive-guide/) explains text objects pretty well.

**Comment by Hi-Angel** [comment]
@noughtmare oh, you're right! I didn't know that visual selection allows to enter `iw` more and more, i.e. I thought it is accepted only just after the switch.

Then, probably, I should fix it the other way than I did now. I ought to leave keybindings as is *(in particular there's nothing to add to Operator.hs)*, and to look at the keybindings for visual mode.

**Comment by jhance** [comment]
Yes, this is why I was confused

**Comment by Hi-Angel** [comment]
Oh, it is so confusing… ☹ I spent a few hours wading through the code, and so far I come up with this: there's a `parseOperand` *(which calls parseCommand)* function which seem to have the magic of choosing a text object, but it seems needs to be called a few times in a row, somehow transformating the return type into its argument.

There's also `textObject` function, which seem to do the magic of *calling `parseOperand` the right way™*, but it is very big, it does a bunch of things, and its type from a *list of operators* to a *single* binding makes me completely lost.

I should thank peoples though, who set comments all over the code — without them I'd spend a few hours in the code.

I'm stuck :(

**Comment by Hi-Angel** [comment]
Oh, I declare the breaktrough, I have to try to work with `stringToTextObject`! I looked at it before, but probably at some point gone to see how it is used, and stuck.

**Comment by ethercrow** [comment]
@Hi-Angel: yes, stringToTextObject is helpful there. I've got `viw` to work here https://github.com/yi-editor/yi/commit/9a93dd9cd68a0ac8d4ac4d6c7c48f8846a77cd68 but it still needs work because vim can also handle counted text objects like `v3iw`

**Comment by Hi-Angel** [comment]
@ethercrow I don't understand, where it is committed? E.g. when I look the [MatchResult.hs](https://github.com/yi-editor/yi/blob/master/src/library/Yi/Keymap/Vim/MatchResult.hs), I didn't see the committed changes. And your fork didn't have them either.

**Comment by noughtmare** [comment]
https://github.com/yi-editor/yi/blob/visual-text-objects/src/library/Yi/Keymap/Vim/MatchResult.hs

**Comment by Hi-Angel** [comment]
I have a question. I can't seem to get to work `trace` with Yi. E.g. I feel like an actual count to a function is actually never passed, so [I'm trying to print](https://gist.github.com/Hi-Angel/eb424afcc8e9c9a55c0373eb22ca9a82#file-gistfile1-txt-L148) its value with [`trace`](https://hackage.haskell.org/package/base-4.9.0.0/docs/Debug-Trace.html#v:trace). But I doesn't see an output of trace anywhere :/ The code with trace definitely get executed, because if I hardcode the count to a number, the behavior changes.

**Comment by Hi-Angel** [comment]
Aha… I seem to find that… The output appears in the `"messages"` buffer. But I didn't see it, because every time new output appears *(and it does appear very often)*, it overwrites the output of `trace`. So the only way to see that output, is to trigger trace while in that buffer, because one more action, and it would disappear.

Is it a bug, or do I do something wrong?

**Comment by ethercrow** [comment]
When I'm working on vim keymap, my usual debugging tools are `stack test --file-watch` and `insertN "this should not happen"`.

**Comment by Hi-Angel** [comment]
@ethercrow well, `stack test` is useful to check that nothing broke, but if something did break, it is often useful to peek at particular values for runtime.

Anyway, while I'm figuring out how to get this branch into my fork *(btw, I figured it out that I should've used `fromMaybe` ☺, don't say that)*, I'd like to bring up a question: is there a particular reason, why [`vsCount`](https://github.com/yi-editor/yi/blob/visual-text-objects/src/library/Yi/Keymap/Vim/Common.hs#L124) is a `Maybe Int`? I mean, `Nothing` is the same as `1`, should we perhaps make it just a `Int` instead?

**Comment by noughtmare** [comment]
@Hi-Angel the `insertN "your runtime error message here` is the command that @ethercrow uses to do his runtime debugging (with the vim keymap).

If `vsCount` was just an `Int` the [`mkDigitBinding`](https://github.com/yi-editor/yi/blob/2f1779b8391b689c36060d053a778ce06f8ee94e/src/library/Yi/Keymap/Vim/VisualMap.hs#L124-L125) function would not function properly anymore, because it wouldn't be able to tell if a digit has already been entered.

**Comment by Hi-Angel** [comment]
[Fixed](https://github.com/yi-editor/yi/commit/9e08919a4669ff0caaf0f01769fa10bc545ef75b).
