### ISSUE TITLE
Discuss versioning of split packages

### ISSUE THREAD

**Issue by jhance** [yi-editor/yi#892]
It sucks that we don't have a great way to create a discussion outside of an issue.

One thing thats concerning to me is that we will only be testing everything against the current release of everything else now.

Should we make our releases all locked against each other in exact versions to guarantee stability? I don't see much that is wrong with this approach - the main benefit of splitting the packages is to make it easier to see how plugins work, and to make it possible to install only a subset of functionality. We don't need flexible dependency management between components.

**Comment by ethercrow** [comment]
I'm in favor of lockstep versioning too.

**Comment by jhance** [comment]
Yay, agreement.

It would also be nice to have a shellscript that generates releases for all the packages (and perhaps publish to hackage, optionally)
