### ISSUE TITLE
The new shining Emacs config triggers an error upon attempt to open a file

### ISSUE THREAD

**Issue by Hi-Angel** [yi-editor/yi#904]
To reproduce:

1. Replace old config with the new static one, i.e. `cp example-configs/yi-emacs-vty-static/Main.hs ~/.config/yi/yi.hs`
2. Run yi, i.e. `stack exec yi`
3. Press <kdb>Ctrl</kdb>+<kdb>x</kdb> <kdb>Ctrl</kdb>+<kdb>f<kdb> to open a new file; an error appears:
	
		[error: /home/constantine/Projects/my-yi-repo/yi/--dyre-master-binary=/home/constantine/Projects/my-yi-repo/yi/.stack-work/install/x86_64-linux/nightly-2016-07-31/8.0.1/bin/.: getDirectoryContents: does not exist (No such file or directory)]

P.S.: the problem is only relevant to `static` config, `dynamic` one works fine.

**Comment by noughtmare** [comment]
You have to build static configs yourself. Try:
1. The same as your 1
2. `cd ~/.config/yi/`
3. Build Yi: `stack build`
4. Run Yi: `stack exec yi-emacs-vty` (yes the executable name has changed, you can change this in by changing the name [under the `executables:` line in package.yaml](https://github.com/yi-editor/yi/blob/master/example-configs/yi-emacs-vty-static/package.yaml#L22)).
3. Do what you want.

I think this should be made much more clear in documentation.

**Comment by Hi-Angel** [comment]
@noughtmare I didn't see the new documentation. Corrections to your comment from my attempt: 1) Copy everything, not just *.hs file, 3) run `stack install`, otherwise `stack exec …` would have nothing to start *(that one just an assumption, but it seems to be right)*, and 4) `stack exec yi` worked for me out of the box, `stack exec yi-emacs-vty` triggered an error about executable not found.

It should be written not *(not only at least)* in documentation, but rather in the examples as a comment. Will you add it? Shall I?

**Comment by Hi-Angel** [comment]
Ah, one more, very important: `stack.yaml` should have a path pointing to yi source code. I built it straight in the source code tree, so it worked for me out of the box; but it won't upon copying to `~/.config/yi`

**Comment by Hi-Angel** [comment]
@noughtmare okay, as you didn't say anything, I'll charge into this.

**Comment by Hi-Angel** [comment]
Well, I made the comments, but I can't seem to find how to commit them into the repository so that it wasn't stacked into the pending commit… I guess I have to wait whilst my pending PR would disappear.

@noughtmare btw, what documentation are you talking about? [I only see 5 pages](https://github.com/yi-editor/yi/wiki) which I seem to see long before, and which didn't seem to say anything about static configs?

**Comment by Hi-Angel** [comment]
[Installing/hacking Yi](http://yi-editor.github.io/pages/installing/) and [Modularizing the config](http://yi-editor.github.io/pages/modular/) didn't even mention the word "static".

**Comment by noughtmare** [comment]
I meant to say that documentation should be written. Sorry for the confusion.

`stack install` will install Yi globally (so you don't have to add `stack exec` to the beginning of your commands*). `stack build` will only install packages locally (in the current stack 'sandbox').

If you didn't change the package.yaml file and you also didn't start Yi with `stack exec yi-emacs-vty` then you can't be running the static version. You are probably running an older version of yi that is still on your path (`stack exec` can run arbitrary programs from your path, e.g. `stack exec firefox` will start firefox).

I thought your first step was to copy the entire folder because I read it to quickly. Actually, you don't need to move the folder at all with the static configs. Only the dynamic configs (the ones that use dyre) need to be moved to your `~/.config/yi` folder. 

* Note: you need to have ~/.local/bin (the location that stack moves executables to) added to your path

**Comment by Hi-Angel** [comment]
@noughtmare 

	$ stack exec yi-emacs-vty
	yi-emacs-vty: user error (RTS doesn't support multiple OS threads (use ghc -threaded when linking))

What would that mean?

**Comment by Hi-Angel** [comment]
@noughtmare @jhance I'm asking an advice for how to shape best the comment about static examples *(in particular because you know more than I do about those configurations)*. Here's a draft:


	-- This is a configuration example, that requires manual rebuild (as opposed to dynamic ones, using
	-- Dyre, which you, probably, actually want). Here's a building example with "stack":
	-- 1. Edit "stack.yaml" file so that "location: " would point to the root of the Yi source code
	-- 2. Run "stack install"
	-- 3. Run the built with "stack exec yi-emacs-vty" (or just "yi-emacs-vty" if you have $PATH
	--    configured acc.)
	-- The final name of the executable can be changed in the "package.yaml" file.

To note:
1. about "location": I modified *(not committed yet)* yaml files so that root directory of the source code could be replaced in the single place
2. I decided to not mention `stack build` because I don't think it would be necessary for end users; and if they configured sandbox, they would probably know its basic idiosyncrasies.

**Comment by noughtmare** [comment]
`yi-emacs-vty: user error (RTS doesn't support multiple OS threads (use ghc -threaded when linking))` means that you have to add `-threaded` to the [`ghc-options`] (https://github.com/yi-editor/yi/blob/master/example-configs/yi-emacs-vty-static/package.yaml#L8) field in the `package.yaml` file. This should be changed by someone (I'm currently changing to a new laptop so I can't do it myself right now). 

As for the documentation. I think it should be written in the installation instructions on the [yi-editor.github.com/pages/installing](yi-editor.github.com/pages/installing) website and in the `README.md`.

**Comment by Hi-Angel** [comment]
@noughtmare okay, I did it, that indeed fixes the problem.

I think that with disregard to documentation, examples should at least explain how to run them. Otherwise there's little point in them.

**Comment by Hi-Angel** [comment]
@noughtmare imagine, one just found a "cool replacement for Vim and Emacs, written in Haskell, what all the cool kids are using", so the first thought: `Aha, so, it's a usual editor I am going to install with package manager, and then search over the internet for example configs`. Does they even think of looking into documentation? Well, at some point, perhaps. But it is fine to expect `I just install it, drop an example config, and see how it's going`.

This is why examples should at least have a comment for how to run them.

**Comment by jhance** [comment]
Seems like thats mostly #902 territory
