### ISSUE TITLE
Feature: module directory manager

### ISSUE THREAD

**Issue by tuncer** [yi-editor/yi#907]
One very nice feature for editing Haskell would be if Yi could automatically manage the directory hierarchy for modules added, renamed, deleted.

**Comment by ethercrow** [comment]
@tuncer do you have a particular plugin for some other editor in mind? So we can ~~shamelessly copy~~ get inspired by it?

**Comment by tuncer** [comment]
I think the Java IDEs do this.

**Comment by jhance** [comment]
Similar: #832
