### ISSUE TITLE
License compatibility with extensions

### ISSUE THREAD

**Issue by tuncer** [yi-editor/yi#908]
Since Yi is GPL2, and extensions are native code, wouldn't it have to have an exception or be licensed as LGPL2 instead, so that extensions can choose to be ISC/BSD/etc?

**Comment by noughtmare** [comment]
To change the license now we would need permission of all contributers (I think that's not possible because this project is quite old).

**Comment by tuncer** [comment]
I've been involved with re-licensing in two big open source projects, so I've seen it work if all past contributors can be reached, or the contributions of those who cannot are easy to rewrite. If it's not easy to rewrite the patches are reverted, which also happened in one of the two projects.

To be clear, I'm not involved enough with Yi to suggest a re-licensing, and I've just been wondering about this today. In fact, doesn't it also mean that my local config is GPL2?

**Comment by noughtmare** [comment]
I would like to see Yi relicensed too, but I was thinking of the AGPL (because running Yi on a server would be pretty awesome). 

Is there a way of licensing Yi that allows extensions to be licensed under a permissive license, but not under a proprietary license? Because I don't think there is and I really don't want proprietary extensions.

**Comment by noughtmare** [comment]
I think your personal Yi config only has to be licensed when you distribute it, so as long as you keep it on your own computer(s) it isn't (yet) GPL-2.

**Comment by ethercrow** [comment]
I'm not a lawyer, but what's the problem of extensions being GPL-2 and running Yi on a server as it is right now?

**Comment by noughtmare** [comment]
Running a (modified) version of Yi on a server without disclosing the source code is legal right now (that's what the AGPL is for). And GPL-2 is bad, because it is outdated ([link](https://www.gnu.org/licenses/rms-why-gplv3.en.html)).

**Comment by ethercrow** [comment]
Wouldn't it be easier and more fun just to rewrite yi in idris under BSD license than to track down all the contributors and convince them to sign something?

**Comment by noughtmare** [comment]
Yes, you are right. Yi is currently not big enough to be ripped off by other companies. Choosing a permissive license is a better option, because it keeps development headache free. And we will always be able to change the license in the future.

**Comment by jhance** [comment]
I think the vast majority of the code (besides us/fuuzetsu) is Don Stewart (probably not difficult to contact) and Jean-Philippe

**Comment by ethercrow** [comment]
@tuncer So do you have something actionable in mind?

**Comment by tuncer** [comment]
Like I said, I'm not involved enough with Yi to be the one who should propose a license change, and I was mainly wondering about the license and what it means for extensions and personal configurations (shared or kept private). If you think changing the license to LGPL or maybe Apache2 or ISC is something you'd like to do, I would support that, and have been involved in two big projects where this happened, so I'm happy to help. Those projects didn't change from copyleft to liberal, and I'm not saying Yi should, but any change requires the same administrative effort and potential un-merge of commits plus maybe rewrite of the code if needed. A simple GPL -> LGPL transition would be enough to resolve compatibility issues.

That said, if you're serious about a rewrite in Idris, I would certainly welcome it, and eager evaluation should make some of it simpler to implement.

**Comment by ethercrow** [comment]
I'm going to close this until someone is ready to propose a new license and manage the transition. Until then we'll get by on everything being GPL-2.
