### ISSUE TITLE
Question: how to assign `Config`?

### ISSUE THREAD

**Issue by Hi-Angel** [yi-editor/yi#909]
I'm trying to port one of [old configs](https://github.com/yi-editor/yi/commit/cd33093fd1787a7327605d193d962b0d303e2752), and I figured out that Yi moved to lens, e.g. `defaultKm = myKeymapSet` now would be `defaultKmA .= keymapSet`.

Now, my problem is that I couldn't get them working, i.e., Yi has such code *(I removed the last part of the function to simlify, and what does matter, is that is still compiles)*:

	configureVim :: ConfigM ()
	configureVim = do
	  defaultKmA         .= keymapSet

It compiles fine. Now, if I copy the same function into my `~/.config/yi/yi.hs` with the relevant imports:

	test :: ConfigM ()
	test = do
		  defaultKmA         .= keymapSet

Compilation fails with:

	/home/constantine/.config/yi/yi.hs:28:10: error:     
		Empty record update

[Acc. to documentation](https://hackage.haskell.org/package/microlens-mtl-0.1.10.0/docs/Lens-Micro-Mtl.html#v:.-61-) here we simply assign to `defaultKmA` the `keymapSet`. And I absolutely don't understand what does compiler want to say.

**Comment by noughtmare** [comment]
It works fine on my machine.

**Comment by Hi-Angel** [comment]
Strange, anyway, thank you, I'll try again later this evening.

**Comment by Hi-Angel** [comment]
Oh, cool, thank you, that works! That turns out was my problem, though I spent a hour or so thinking that I didn't get something with lens :Ь Thank you
