### ISSUE TITLE
Unable to import modules in config

### ISSUE THREAD

**Issue by zanzix** [yi-editor/yi#915]
I recently installed yi using Stack on ubuntu and was trying to edit the config.

I tried using one of the default configs - the emacs one - however when I reloaded Yi, it gave me an error for every module that I tried to import, saying that the file was not found.

What could I do to fix this?

Here is the error exactly.

```
/home/zans/.config/yi/yi.hs:1:18:
    Could not find module ‘Lens.Micro.Platform’
    Use -v to see a list of the files searched for.

/home/zans/.config/yi/yi.hs:2:18:
    Could not find module ‘Yi’
    Use -v to see a list of the files searched for.

/home/zans/.config/yi/yi.hs:3:18:
    Could not find module ‘Yi.Config.Default.Emacs’
    Use -v to see a list of the files searched for.

/home/zans/.config/yi/yi.hs:4:18:
    Could not find module ‘Yi.Config.Default.HaskellMode’
    Use -v to see a list of the files searched for.

/home/zans/.config/yi/yi.hs:5:18:
    Could not find module ‘Yi.Config.Default.JavaScriptMode’
    Use -v to see a list of the files searched for.

/home/zans/.config/yi/yi.hs:6:18:
    Could not find module ‘Yi.Config.Default.MiscModes’
    Use -v to see a list of the files searched for.

/home/zans/.config/yi/yi.hs:7:18:
    Could not find module ‘Yi.Config.Default.Vty’
    Use -v to see a list of the files searched for.

/home/zans/.config/yi/yi.hs:8:18:
    Could not find module ‘Yi.Config.Simple’
    Use -v to see a list of the files searched for.

/home/zans/.config/yi/yi.hs:9:18:
    Could not find module ‘Yi.Keymap.Emacs’
    Use -v to see a list of the files searched for.

/home/zans/.config/yi/yi.hs:10:18:
    Could not find module ‘Yi.Rope’
    Use -v to see a list of the files searched for.

/home/zans/.config/yi/yi.hs:11:18:
    Could not find module ‘Yi.String’
    Use -v to see a list of the files searched for.
```

**Comment by Hi-Angel** [comment]
A shot in the dark, perhaps could that be because stack has the source before [the "split packages" merge](https://github.com/yi-editor/yi/commit/d03ac79dc6623fa6b710bfe886fdea56ea51031b)? I couldn't unfortunately find an analog to cabal "fetch" option in the stack to compare ☹

**Comment by Hi-Angel** [comment]
Oh, sorry, I linked the wrong revision, fixed.

@zanzix can you [try this old config](https://github.com/yi-editor/yi/blob/8f99ba6e6dc49ff71f50607ace54d186de7f7be8/example-configs/yi-simple.hs)? I.e. if I guessed the problem, this should compile just fine.

**Comment by zanzix** [comment]
@Hi-Angel thanks for your input.
I tried the old config, it still gives me the same type of error "Could not find module Yi" and the same for Yi.Keymap.Emacs and Yi.String

**Comment by zanzix** [comment]
I reinstalled Yi from source to avoid this issue.

**Comment by bijoutrouvaille** [comment]
I'm only starting with the editor, but running it using `stack exec yi` seems to work for me.
