### ISSUE TITLE
Can't access function I defined in my Config in the mini-buffer (emacs mode)

### ISSUE THREAD

**Issue by zanzix** [yi-editor/yi#916]
I'm just starting off with Yi and I added a helloWorld :: BufferM() function to the yi.hs config file.

However when I run Yi and press M-x the helloWorld function is not listed there, and running "helloWorld" does not do anything either.

What am I missing?

**Comment by noughtmare** [comment]
http://yi-editor.github.io/pages/about-M-x/

**Comment by zanzix** [comment]
Thank you for the explanation, noughtmare :)
