### ISSUE TITLE
Speed up travis build

### ISSUE THREAD

**Issue by ethercrow** [yi-editor/yi#924]
For every example config, all yi-\* packages and extra deps are recompiled again and again. It must be a way to share .stack-work dir or reuse built packages in some other way.

**Comment by ethercrow** [comment]
Beware of https://github.com/commercialhaskell/stack/issues/1731

**Comment by SShrike** [comment]
There are build caches on Travis, I believe you can specify custom directories.

**Comment by ethercrow** [comment]
We already use build cache for $HOME/.stack, but that doesn't help in this particular case. Caching `example-config/*/.stack-work` would be wrong as it would reuse stuff from other revisions.

**Comment by noughtmare** [comment]
I think dependencies will stay if we would only build the main yi executable multiple times with different flags.

**Comment by ethercrow** [comment]
Example configs now share stack work directory: https://github.com/yi-editor/yi/commit/41627755aed2698039be4ba9ae0bce8a8457d248
