### ISSUE TITLE
(minimal problem) Yi.Keymap.Vim.Eval: couldn't found 'vimEval'

### ISSUE THREAD

**Issue by aiya000** [yi-editor/yi#929]
I found the problem in [here](https://www.stackage.org/haddock/lts-7.4/yi-0.12.6/Yi-Keymap-Vim-Eval.html).
I think that is 'pureEval'.

**Comment by ethercrow** [comment]
Nice catch, thanks!

**Comment by ethercrow** [comment]
Fixed in https://github.com/yi-editor/yi/commit/2f0c7b738b3a1f79ff149034db2c4392273ee26f

**Comment by aiya000** [comment]
Thanks :+1:
