### ISSUE TITLE
identString didn't work as the document example

### ISSUE THREAD

**Issue by aiya000** [yi-editor/yi#937]
I executed `stack haddock` and saw the page of `shortIdentString` and `identString` .  
I saw this example .

```
>>> shortIdentString 3 (MemBuffer "hello")
"*hello*"
>>> shortIdentString 3 (FileBuffer "hello")
"lo"
```

```
>>> identString (MemBuffer "hello")
"*hello*"
>>> identString (FileBuffer "hello")
"hello"
```

I execute `stack ghci` and this .  
And I got the errors .
```
>>> identString (MemBuffer "hello")
<interactive>:2:14-26: error:
    • Couldn't match expected type ‘FBuffer’
                  with actual type ‘BufferId’
    • In the first argument of ‘identString’, namely ‘(MemBuffer "a")’
      In the expression: identString (MemBuffer "a")
      In an equation for ‘it’: it = identString (MemBuffer "a")

```
Is the document wrong ? :thinking:

**Comment by jhance** [comment]
Documentation is definitely wrong.

```
shortIdentString dl b = case b ^. identA of
```

The first thing the function is extract the `BufferId` from the `FBuffer`. It doesn't use any other parts of the `FBuffer`. So it could be changed to take a `BufferId` instead.

**Comment by aiya000** [comment]
Thanks :smile:

Can I fix with [this PR](https://github.com/yi-editor/yi/pull/938/commits/ae721e4a4accb8da007ba59e6536e58a07295e5d) ?

Sorry, I'm worried

- Is how to make FBuffer correct with the pure functions ?
- The purpose of shortIdentString was modified

**Comment by aiya000** [comment]
[PR](https://github.com/yi-editor/yi/pull/938/commits/ae721e4a4accb8da007ba59e6536e58a07295e5d) leaves from WIP .

Please accept it if it is good :smiley:
