### ISSUE TITLE
Errors during installation on OS X 

### ISSUE THREAD

**Issue by rprechelt** [yi-editor/yi#939]
On a brand new fresh OS X installation, with a new `cabal` install, following the instructions [here](https://yi-editor.github.io/pages/installing/) resulted in a plethora of errors (alex not found, wrong version of alex, happy not found). After much trial and error (and several restarts with fresh cabal installations), the following command list got the furthest towards installation. 

    cabal update
    cabal install alex-3.1.7
    brew install icu4c
    cabal install text-icu --extra-lib-dirs=/usr/local/opt/icu4c/lib --extra-include-dirs=/usr/local/opt/icu4c/include
    cabal install happy
    brew install pkg-config
    cabal install yi --extra-lib-dirs=/usr/local/opt/icu4c/lib --extra-include-dirs=/usr/local/opt/icu4c/include

However, this results in the following error: 

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: yi-frontend-vty-0.13.3/installed-6aY... (dependency of yi-0.13.3:+vty)
trying: yi-frontend-pango-0.13.3 (dependency of yi-0.13.3:+pango)
next goal: pango (dependency of yi-frontend-pango-0.13.3)
rejecting: pango-0.13.3.1, pango-0.13.3.0, pango-0.13.2.0, pango-0.13.1.1,
pango-0.13.1.0, pango-0.13.0.5, pango-0.13.0.4, pango-0.13.0.3,
pango-0.13.0.2, pango-0.13.0.1 (conflict: requires pkg-config package
cairo>=1.2.0, not found in the pkg-config database)
rejecting: pango-0.13.0.0 (conflict: yi-frontend-vty =>
text==1.2.2.1/installed-9Yh..., pango => text>=0.11.0.6 && <1.2)
rejecting: pango-0.12.5.3, pango-0.12.5.0, pango-0.12.4, pango-0.12.3,
pango-0.12.2, pango-0.12.1, pango-0.12.0, pango-0.11.2, pango-0.11.1,
pango-0.11.0 (conflict: yi-frontend-pango => pango>=0.13 && <0.14)
Backjump limit reached (currently 5000, change with --max-backjumps or try to
run with --reorder-goals).
```

Still cannot get `yi` installed on OS X. Any recommendations?

**Comment by ethercrow** [comment]
> requires pkg-config package cairo>=1.2.0, not found in the pkg-config database

brew install cairo

Additionally, I've only been able to build pango frontend on OSX if `gtk` package was built with `have-quartz-gtk` flag

Subjectively the easiest way to get to usable state is to clone this repo, cd into one of the static examples and run `stack install --extra-lib-dirs=/usr/local/opt/icu4c/lib --extra-include-dirs=/usr/local/opt/icu4c/include`

**Comment by ethercrow** [comment]
I'm going to close this, feel free to reopen if you have more questions.

If you can find the time for a documentation pull request, that would be awesome.
