### ISSUE TITLE
Seems like I cannot build/install v0.13.4 with stack.

### ISSUE THREAD

**Issue by Magicloud** [yi-editor/yi#945]
-   stack failed as "In the dependencies for yi-0.13.4: optparse-applicative-0.12.1.0 must match >=0.13.0.0 (latest applicable is 0.13.0.0)"

**Comment by ethercrow** [comment]
> cabal from hackage failed due to some type mismatch in yi-language

This is because of still unfixed https://github.com/yi-editor/yi/issues/922

> stack failed as "In the dependencies for yi-0.13.4: optparse-applicative-0.12.1.0 must match >=0.13.0.0 (latest applicable is 0.13.0.0)"

This is because I accidentally broke stack.yaml. You can try changing the version there to fix the build locally. I'm sorry for this breakage, I'll fix it as soon as I have some free time.

**Comment by Magicloud** [comment]
Thank you. I found #922 , so removed cabal items later.
