### ISSUE TITLE
repository fails "git fsck"

### ISSUE THREAD

**Issue by realcomplex** [yi-editor/yi#959]
```
yi > git fsck                                     
Checking object directories: 100% (256/256), done.
error in commit 5da7b4e51a48152cccbc8f28952e0f30d94b6100: missingNameBeforeEmail: invalid author/committer line - missing space before email
Checking objects: 100% (40696/40696), done.
```
This results in a fatal error when trying to clone the repository and the `transfer.fsckObjects = true` option is set in `.gitconfig`, for example:
```
~ > git clone https://github.com/yi-editor/yi.git
Cloning into 'yi'...
remote: Counting objects: 40696, done.
remote: Compressing objects: 100% (117/117), done.
error: object 5da7b4e51a48152cccbc8f28952e0f30d94b6100: missingNameBeforeEmail: invalid author/committer line - missing space before email
fatal: Error in object
fatal: index-pack failed
```

**Comment by ethercrow** [comment]
Do you know how to solve it?

**Comment by realcomplex** [comment]
I don't, but if I have time later today I'll see if I can find a fix.

**Comment by realcomplex** [comment]
Alright, so there is a commit with a bas author field, but that commit would be hard to fix without rewriting a lot of history. Since a bad author field is not a big problem, the fix that I recommend is to use the `fsck.skipList`: create a file in the .git directory called `fsck_skipList`, and in `.git/config` set  `fsck.skipList = .git/fsck_skipList`. Run `git fsck` to confirm that everything works nicely.

**Comment by Fuuzetsu** [comment]
I could have sworn we had this discussion before but I don't see a ticket…

Ah, it was a private e-mail in 2014. The conclusion there was that we can't to anything about it without rewriting years worth of history. There was some script which tried to fix the problem if we decided to do that. I'm in favour of of skipList thing personally.

**Comment by ethercrow** [comment]
Do I understand correctly that skipList workaround is done only on user's machine and we don't have to change the central repository?

**Comment by Fuuzetsu** [comment]
I believe you can set it in repo so it works for everyone

**Comment by ethercrow** [comment]
I added .fsck-skiplist: https://github.com/yi-editor/yi/blob/master/.fsck-skiplist

But I couldn't figure out a way to impose this piece of git config on anyone who clones the repo.
